// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ActionEvent
    /// </summary>
    public partial class ActionEvent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionEvent" /> class.
        /// </summary>
        /// <param name="bodyAsJson">bodyAsJson</param>
        [JsonConstructor]
        public ActionEvent(Option<string?> bodyAsJson = default)
        {
            BodyAsJsonOption = bodyAsJson;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of BodyAsJson
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BodyAsJsonOption { get; private set; }

        /// <summary>
        /// Gets or Sets BodyAsJson
        /// </summary>
        [JsonPropertyName("bodyAsJson")]
        public string? BodyAsJson { get { return this.BodyAsJsonOption; } set { this.BodyAsJsonOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActionEvent {\n");
            sb.Append("  BodyAsJson: ").Append(BodyAsJson).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ActionEvent" />
    /// </summary>
    public class ActionEventJsonConverter : JsonConverter<ActionEvent>
    {
        /// <summary>
        /// Deserializes json to <see cref="ActionEvent" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ActionEvent Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> bodyAsJson = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "bodyAsJson":
                            bodyAsJson = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (bodyAsJson.IsSet && bodyAsJson.Value == null)
                throw new ArgumentNullException(nameof(bodyAsJson), "Property is not nullable for class ActionEvent.");

            return new ActionEvent(bodyAsJson);
        }

        /// <summary>
        /// Serializes a <see cref="ActionEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="actionEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ActionEvent actionEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, actionEvent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ActionEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="actionEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ActionEvent actionEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            if (actionEvent.BodyAsJsonOption.IsSet && actionEvent.BodyAsJson == null)
                throw new ArgumentNullException(nameof(actionEvent.BodyAsJson), "Property is required for class ActionEvent.");

            if (actionEvent.BodyAsJsonOption.IsSet)
                writer.WriteString("bodyAsJson", actionEvent.BodyAsJson);
        }
    }
}
