// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BulkCancelEventResponse
    /// </summary>
    public partial class BulkCancelEventResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkCancelEventResponse" /> class.
        /// </summary>
        /// <param name="triggerKey">Trigger key related to the canceled event.</param>
        /// <param name="results">List of results for each item in the bulk cancel event request.</param>
        /// <param name="bulkActionMetadata">Metadata for the overall bulk action, including success and failure counts.</param>
        [JsonConstructor]
        public BulkCancelEventResponse(Option<string?> triggerKey = default, Option<List<Object>?> results = default, Option<Object?> bulkActionMetadata = default)
        {
            TriggerKeyOption = triggerKey;
            ResultsOption = results;
            BulkActionMetadataOption = bulkActionMetadata;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TriggerKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TriggerKeyOption { get; private set; }

        /// <summary>
        /// Trigger key related to the canceled event.
        /// </summary>
        /// <value>Trigger key related to the canceled event.</value>
        [JsonPropertyName("triggerKey")]
        public string? TriggerKey { get { return this.TriggerKeyOption; } set { this.TriggerKeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Results
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Object>?> ResultsOption { get; private set; }

        /// <summary>
        /// List of results for each item in the bulk cancel event request.
        /// </summary>
        /// <value>List of results for each item in the bulk cancel event request.</value>
        [JsonPropertyName("results")]
        public List<Object>? Results { get { return this.ResultsOption; } set { this.ResultsOption = new(value); } }

        /// <summary>
        /// Used to track the state of BulkActionMetadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> BulkActionMetadataOption { get; private set; }

        /// <summary>
        /// Metadata for the overall bulk action, including success and failure counts.
        /// </summary>
        /// <value>Metadata for the overall bulk action, including success and failure counts.</value>
        [JsonPropertyName("bulkActionMetadata")]
        public Object? BulkActionMetadata { get { return this.BulkActionMetadataOption; } set { this.BulkActionMetadataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkCancelEventResponse {\n");
            sb.Append("  TriggerKey: ").Append(TriggerKey).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  BulkActionMetadata: ").Append(BulkActionMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TriggerKey (string) maxLength
            if (this.TriggerKey != null && this.TriggerKey.Length > 100)
            {
                yield return new ValidationResult("Invalid value for TriggerKey, length must be less than 100.", new [] { "TriggerKey" });
            }

            // TriggerKey (string) minLength
            if (this.TriggerKey != null && this.TriggerKey.Length < 1)
            {
                yield return new ValidationResult("Invalid value for TriggerKey, length must be greater than 1.", new [] { "TriggerKey" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BulkCancelEventResponse" />
    /// </summary>
    public class BulkCancelEventResponseJsonConverter : JsonConverter<BulkCancelEventResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="BulkCancelEventResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BulkCancelEventResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> triggerKey = default;
            Option<List<Object>?> results = default;
            Option<Object?> bulkActionMetadata = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "triggerKey":
                            triggerKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "results":
                            results = new Option<List<Object>?>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "bulkActionMetadata":
                            bulkActionMetadata = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (triggerKey.IsSet && triggerKey.Value == null)
                throw new ArgumentNullException(nameof(triggerKey), "Property is not nullable for class BulkCancelEventResponse.");

            if (results.IsSet && results.Value == null)
                throw new ArgumentNullException(nameof(results), "Property is not nullable for class BulkCancelEventResponse.");

            if (bulkActionMetadata.IsSet && bulkActionMetadata.Value == null)
                throw new ArgumentNullException(nameof(bulkActionMetadata), "Property is not nullable for class BulkCancelEventResponse.");

            return new BulkCancelEventResponse(triggerKey, results, bulkActionMetadata);
        }

        /// <summary>
        /// Serializes a <see cref="BulkCancelEventResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkCancelEventResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BulkCancelEventResponse bulkCancelEventResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, bulkCancelEventResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BulkCancelEventResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bulkCancelEventResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BulkCancelEventResponse bulkCancelEventResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (bulkCancelEventResponse.TriggerKeyOption.IsSet && bulkCancelEventResponse.TriggerKey == null)
                throw new ArgumentNullException(nameof(bulkCancelEventResponse.TriggerKey), "Property is required for class BulkCancelEventResponse.");

            if (bulkCancelEventResponse.ResultsOption.IsSet && bulkCancelEventResponse.Results == null)
                throw new ArgumentNullException(nameof(bulkCancelEventResponse.Results), "Property is required for class BulkCancelEventResponse.");

            if (bulkCancelEventResponse.BulkActionMetadataOption.IsSet && bulkCancelEventResponse.BulkActionMetadata == null)
                throw new ArgumentNullException(nameof(bulkCancelEventResponse.BulkActionMetadata), "Property is required for class BulkCancelEventResponse.");

            if (bulkCancelEventResponse.TriggerKeyOption.IsSet)
                writer.WriteString("triggerKey", bulkCancelEventResponse.TriggerKey);

            if (bulkCancelEventResponse.ResultsOption.IsSet)
            {
                writer.WritePropertyName("results");
                JsonSerializer.Serialize(writer, bulkCancelEventResponse.Results, jsonSerializerOptions);
            }
            if (bulkCancelEventResponse.BulkActionMetadataOption.IsSet)
            {
                writer.WritePropertyName("bulkActionMetadata");
                JsonSerializer.Serialize(writer, bulkCancelEventResponse.BulkActionMetadata, jsonSerializerOptions);
            }
        }
    }
}
