// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines CancellationReason
    /// </summary>
    public enum CancellationReason
    {
        /// <summary>
        /// Enum Order1valueEVENTCANCELLEDdescriptionIndicatesThatTheActivationWasCancelledDirectlymaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:1,\&quot;value\&quot;:\&quot;EVENT_CANCELLED\&quot;,\&quot;description\&quot;:\&quot;Indicates that the activation was cancelled directly.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
        /// </summary>
        Order1valueEVENTCANCELLEDdescriptionIndicatesThatTheActivationWasCancelledDirectlymaturityGAexposurePUBLIC = 1,

        /// <summary>
        /// Enum Order2valueAUTOMATIONDEACTIVATEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeactivatedmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:2,\&quot;value\&quot;:\&quot;AUTOMATION_DEACTIVATED\&quot;,\&quot;description\&quot;:\&quot;Indicates that the activation was cancelled because the automation was deactivated.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
        /// </summary>
        Order2valueAUTOMATIONDEACTIVATEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeactivatedmaturityGAexposurePUBLIC = 2,

        /// <summary>
        /// Enum Order3valueAUTOMATIONDELETEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeletedmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:3,\&quot;value\&quot;:\&quot;AUTOMATION_DELETED\&quot;,\&quot;description\&quot;:\&quot;Indicates that the activation was cancelled because the automation was deleted.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
        /// </summary>
        Order3valueAUTOMATIONDELETEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeletedmaturityGAexposurePUBLIC = 3,

        /// <summary>
        /// Enum Order4valueCANCELLEDBYREFRESHPAYLOADdescriptionIndicatesThatTheActivationWasCancelledAfterTheAutomationScheduleTimeWasReachedmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:4,\&quot;value\&quot;:\&quot;CANCELLED_BY_REFRESH_PAYLOAD\&quot;,\&quot;description\&quot;:\&quot;Indicates that the activation was cancelled after the automation schedule time was reached.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
        /// </summary>
        Order4valueCANCELLEDBYREFRESHPAYLOADdescriptionIndicatesThatTheActivationWasCancelledAfterTheAutomationScheduleTimeWasReachedmaturityGAexposurePUBLIC = 4,

        /// <summary>
        /// Enum Order5valueCANCELLEDBYGDPRREQUESTdescriptionIndicatesThatTheActivationWasCancelledDueToAUoUGDPRRightToBeForgottenRequestmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:5,\&quot;value\&quot;:\&quot;CANCELLED_BY_GDPR_REQUEST\&quot;,\&quot;description\&quot;:\&quot;Indicates that the activation was cancelled due to a UoU GDPR \&quot;Right to be Forgotten\&quot; request.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
        /// </summary>
        Order5valueCANCELLEDBYGDPRREQUESTdescriptionIndicatesThatTheActivationWasCancelledDueToAUoUGDPRRightToBeForgottenRequestmaturityGAexposurePUBLIC = 5
    }

    /// <summary>
    /// Converts <see cref="CancellationReason"/> to and from the JSON value
    /// </summary>
    public static class CancellationReasonValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="CancellationReason"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CancellationReason FromString(string value)
        {
            if (value.Equals("{\"order\":1,\"value\":\"EVENT_CANCELLED\",\"description\":\"Indicates that the activation was cancelled directly.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order1valueEVENTCANCELLEDdescriptionIndicatesThatTheActivationWasCancelledDirectlymaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":2,\"value\":\"AUTOMATION_DEACTIVATED\",\"description\":\"Indicates that the activation was cancelled because the automation was deactivated.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order2valueAUTOMATIONDEACTIVATEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeactivatedmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":3,\"value\":\"AUTOMATION_DELETED\",\"description\":\"Indicates that the activation was cancelled because the automation was deleted.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order3valueAUTOMATIONDELETEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeletedmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":4,\"value\":\"CANCELLED_BY_REFRESH_PAYLOAD\",\"description\":\"Indicates that the activation was cancelled after the automation schedule time was reached.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order4valueCANCELLEDBYREFRESHPAYLOADdescriptionIndicatesThatTheActivationWasCancelledAfterTheAutomationScheduleTimeWasReachedmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":5,\"value\":\"CANCELLED_BY_GDPR_REQUEST\",\"description\":\"Indicates that the activation was cancelled due to a UoU GDPR \"Right to be Forgotten\" request.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order5valueCANCELLEDBYGDPRREQUESTdescriptionIndicatesThatTheActivationWasCancelledDueToAUoUGDPRRightToBeForgottenRequestmaturityGAexposurePUBLIC;

            throw new NotImplementedException($"Could not convert value to type CancellationReason: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="CancellationReason"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CancellationReason? FromStringOrDefault(string value)
        {
            if (value.Equals("{\"order\":1,\"value\":\"EVENT_CANCELLED\",\"description\":\"Indicates that the activation was cancelled directly.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order1valueEVENTCANCELLEDdescriptionIndicatesThatTheActivationWasCancelledDirectlymaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":2,\"value\":\"AUTOMATION_DEACTIVATED\",\"description\":\"Indicates that the activation was cancelled because the automation was deactivated.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order2valueAUTOMATIONDEACTIVATEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeactivatedmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":3,\"value\":\"AUTOMATION_DELETED\",\"description\":\"Indicates that the activation was cancelled because the automation was deleted.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order3valueAUTOMATIONDELETEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeletedmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":4,\"value\":\"CANCELLED_BY_REFRESH_PAYLOAD\",\"description\":\"Indicates that the activation was cancelled after the automation schedule time was reached.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order4valueCANCELLEDBYREFRESHPAYLOADdescriptionIndicatesThatTheActivationWasCancelledAfterTheAutomationScheduleTimeWasReachedmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":5,\"value\":\"CANCELLED_BY_GDPR_REQUEST\",\"description\":\"Indicates that the activation was cancelled due to a UoU GDPR \"Right to be Forgotten\" request.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return CancellationReason.Order5valueCANCELLEDBYGDPRREQUESTdescriptionIndicatesThatTheActivationWasCancelledDueToAUoUGDPRRightToBeForgottenRequestmaturityGAexposurePUBLIC;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CancellationReason"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(CancellationReason value)
        {
            if (value == CancellationReason.Order1valueEVENTCANCELLEDdescriptionIndicatesThatTheActivationWasCancelledDirectlymaturityGAexposurePUBLIC)
                return "{\"order\":1,\"value\":\"EVENT_CANCELLED\",\"description\":\"Indicates that the activation was cancelled directly.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == CancellationReason.Order2valueAUTOMATIONDEACTIVATEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeactivatedmaturityGAexposurePUBLIC)
                return "{\"order\":2,\"value\":\"AUTOMATION_DEACTIVATED\",\"description\":\"Indicates that the activation was cancelled because the automation was deactivated.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == CancellationReason.Order3valueAUTOMATIONDELETEDdescriptionIndicatesThatTheActivationWasCancelledBecauseTheAutomationWasDeletedmaturityGAexposurePUBLIC)
                return "{\"order\":3,\"value\":\"AUTOMATION_DELETED\",\"description\":\"Indicates that the activation was cancelled because the automation was deleted.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == CancellationReason.Order4valueCANCELLEDBYREFRESHPAYLOADdescriptionIndicatesThatTheActivationWasCancelledAfterTheAutomationScheduleTimeWasReachedmaturityGAexposurePUBLIC)
                return "{\"order\":4,\"value\":\"CANCELLED_BY_REFRESH_PAYLOAD\",\"description\":\"Indicates that the activation was cancelled after the automation schedule time was reached.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == CancellationReason.Order5valueCANCELLEDBYGDPRREQUESTdescriptionIndicatesThatTheActivationWasCancelledDueToAUoUGDPRRightToBeForgottenRequestmaturityGAexposurePUBLIC)
                return "{\"order\":5,\"value\":\"CANCELLED_BY_GDPR_REQUEST\",\"description\":\"Indicates that the activation was cancelled due to a UoU GDPR \"Right to be Forgotten\" request.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CancellationReason"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class CancellationReasonJsonConverter : JsonConverter<CancellationReason>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CancellationReason Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            CancellationReason? result = rawValue == null
                ? null
                : CancellationReasonValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CancellationReason to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cancellationReason"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CancellationReason cancellationReason, JsonSerializerOptions options)
        {
            writer.WriteStringValue(CancellationReasonValueConverter.ToJsonValue(cancellationReason).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CancellationReason"/>
    /// </summary>
    public class CancellationReasonNullableJsonConverter : JsonConverter<CancellationReason?>
    {
        /// <summary>
        /// Returns a CancellationReason from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CancellationReason? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            CancellationReason? result = rawValue == null
                ? null
                : CancellationReasonValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CancellationReason to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cancellationReason"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CancellationReason? cancellationReason, JsonSerializerOptions options)
        {
            writer.WriteStringValue(cancellationReason.HasValue ? CancellationReasonValueConverter.ToJsonValue(cancellationReason.Value).ToString() : "null");
        }
    }
}
