// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CreateGiftCardResponse1
    /// </summary>
    public partial class CreateGiftCardResponse1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateGiftCardResponse1" /> class.
        /// </summary>
        /// <param name="giftCard">giftCard</param>
        [JsonConstructor]
        public CreateGiftCardResponse1(Option<GiftCard1?> giftCard = default)
        {
            GiftCardOption = giftCard;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of GiftCard
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GiftCard1?> GiftCardOption { get; private set; }

        /// <summary>
        /// Gets or Sets GiftCard
        /// </summary>
        [JsonPropertyName("giftCard")]
        public GiftCard1? GiftCard { get { return this.GiftCardOption; } set { this.GiftCardOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateGiftCardResponse1 {\n");
            sb.Append("  GiftCard: ").Append(GiftCard).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateGiftCardResponse1" />
    /// </summary>
    public class CreateGiftCardResponse1JsonConverter : JsonConverter<CreateGiftCardResponse1>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateGiftCardResponse1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateGiftCardResponse1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<GiftCard1?> giftCard = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "giftCard":
                            giftCard = new Option<GiftCard1?>(JsonSerializer.Deserialize<GiftCard1>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (giftCard.IsSet && giftCard.Value == null)
                throw new ArgumentNullException(nameof(giftCard), "Property is not nullable for class CreateGiftCardResponse1.");

            return new CreateGiftCardResponse1(giftCard);
        }

        /// <summary>
        /// Serializes a <see cref="CreateGiftCardResponse1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createGiftCardResponse1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateGiftCardResponse1 createGiftCardResponse1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createGiftCardResponse1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateGiftCardResponse1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createGiftCardResponse1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateGiftCardResponse1 createGiftCardResponse1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createGiftCardResponse1.GiftCardOption.IsSet && createGiftCardResponse1.GiftCard == null)
                throw new ArgumentNullException(nameof(createGiftCardResponse1.GiftCard), "Property is required for class CreateGiftCardResponse1.");

            if (createGiftCardResponse1.GiftCardOption.IsSet)
            {
                writer.WritePropertyName("giftCard");
                JsonSerializer.Serialize(writer, createGiftCardResponse1.GiftCard, jsonSerializerOptions);
            }
        }
    }
}
