// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DraftInfo
    /// </summary>
    public partial class DraftInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DraftInfo" /> class.
        /// </summary>
        /// <param name="originalAutomationId">Optional - automationId of the original automation.</param>
        [JsonConstructor]
        internal DraftInfo(Option<string?> originalAutomationId = default)
        {
            OriginalAutomationIdOption = originalAutomationId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of OriginalAutomationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OriginalAutomationIdOption { get; }

        /// <summary>
        /// Optional - automationId of the original automation.
        /// </summary>
        /// <value>Optional - automationId of the original automation.</value>
        [JsonPropertyName("originalAutomationId")]
        public string? OriginalAutomationId { get { return this.OriginalAutomationIdOption; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DraftInfo {\n");
            sb.Append("  OriginalAutomationId: ").Append(OriginalAutomationId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DraftInfo" />
    /// </summary>
    public class DraftInfoJsonConverter : JsonConverter<DraftInfo>
    {
        /// <summary>
        /// Deserializes json to <see cref="DraftInfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DraftInfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> originalAutomationId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "originalAutomationId":
                            originalAutomationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (originalAutomationId.IsSet && originalAutomationId.Value == null)
                throw new ArgumentNullException(nameof(originalAutomationId), "Property is not nullable for class DraftInfo.");

            return new DraftInfo(originalAutomationId);
        }

        /// <summary>
        /// Serializes a <see cref="DraftInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="draftInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DraftInfo draftInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, draftInfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DraftInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="draftInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DraftInfo draftInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (draftInfo.OriginalAutomationIdOption.IsSet && draftInfo.OriginalAutomationId == null)
                throw new ArgumentNullException(nameof(draftInfo.OriginalAutomationId), "Property is required for class DraftInfo.");

            if (draftInfo.OriginalAutomationIdOption.IsSet)
                writer.WriteString("originalAutomationId", draftInfo.OriginalAutomationId);
        }
    }
}
