// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Information about an external event that lead to the transaction.
    /// </summary>
    public partial class ExternalEvent1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalEvent1" /> class.
        /// </summary>
        /// <param name="name">Event type indicator</param>
        /// <param name="description">Short description or identifier of the event</param>
        [JsonConstructor]
        public ExternalEvent1(Option<NameEnum?> name = default, Option<string?> description = default)
        {
            NameOption = name;
            DescriptionOption = description;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Event type indicator
        /// </summary>
        /// <value>Event type indicator</value>
        public enum NameEnum
        {
            /// <summary>
            /// Enum ORDER for value: ORDER
            /// </summary>
            ORDER = 1,

            /// <summary>
            /// Enum REFUND for value: REFUND
            /// </summary>
            REFUND = 2,

            /// <summary>
            /// Enum REFERRAL for value: REFERRAL
            /// </summary>
            REFERRAL = 3,

            /// <summary>
            /// Enum SIGNUP for value: SIGN_UP
            /// </summary>
            SIGNUP = 4,

            /// <summary>
            /// Enum MEMBERSHIP for value: MEMBERSHIP
            /// </summary>
            MEMBERSHIP = 5,

            /// <summary>
            /// Enum COMPENSATION for value: COMPENSATION
            /// </summary>
            COMPENSATION = 6,

            /// <summary>
            /// Enum OTHER for value: OTHER
            /// </summary>
            OTHER = 7
        }

        /// <summary>
        /// Returns a <see cref="NameEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static NameEnum NameEnumFromString(string value)
        {
            if (value.Equals("ORDER"))
                return NameEnum.ORDER;

            if (value.Equals("REFUND"))
                return NameEnum.REFUND;

            if (value.Equals("REFERRAL"))
                return NameEnum.REFERRAL;

            if (value.Equals("SIGN_UP"))
                return NameEnum.SIGNUP;

            if (value.Equals("MEMBERSHIP"))
                return NameEnum.MEMBERSHIP;

            if (value.Equals("COMPENSATION"))
                return NameEnum.COMPENSATION;

            if (value.Equals("OTHER"))
                return NameEnum.OTHER;

            throw new NotImplementedException($"Could not convert value to type NameEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="NameEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NameEnum? NameEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ORDER"))
                return NameEnum.ORDER;

            if (value.Equals("REFUND"))
                return NameEnum.REFUND;

            if (value.Equals("REFERRAL"))
                return NameEnum.REFERRAL;

            if (value.Equals("SIGN_UP"))
                return NameEnum.SIGNUP;

            if (value.Equals("MEMBERSHIP"))
                return NameEnum.MEMBERSHIP;

            if (value.Equals("COMPENSATION"))
                return NameEnum.COMPENSATION;

            if (value.Equals("OTHER"))
                return NameEnum.OTHER;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="NameEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string NameEnumToJsonValue(NameEnum? value)
        {
            if (value == NameEnum.ORDER)
                return "ORDER";

            if (value == NameEnum.REFUND)
                return "REFUND";

            if (value == NameEnum.REFERRAL)
                return "REFERRAL";

            if (value == NameEnum.SIGNUP)
                return "SIGN_UP";

            if (value == NameEnum.MEMBERSHIP)
                return "MEMBERSHIP";

            if (value == NameEnum.COMPENSATION)
                return "COMPENSATION";

            if (value == NameEnum.OTHER)
                return "OTHER";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NameEnum?> NameOption { get; private set; }

        /// <summary>
        /// Event type indicator
        /// </summary>
        /// <value>Event type indicator</value>
        [JsonPropertyName("name")]
        public NameEnum? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Short description or identifier of the event
        /// </summary>
        /// <value>Short description or identifier of the event</value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExternalEvent1 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 300)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 300.", new [] { "Description" });
            }

            // Description (string) minLength
            if (this.Description != null && this.Description.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Description, length must be greater than 1.", new [] { "Description" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExternalEvent1" />
    /// </summary>
    public class ExternalEvent1JsonConverter : JsonConverter<ExternalEvent1>
    {
        /// <summary>
        /// Deserializes json to <see cref="ExternalEvent1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExternalEvent1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ExternalEvent1.NameEnum?> name = default;
            Option<string?> description = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            string? nameRawValue = utf8JsonReader.GetString();
                            if (nameRawValue != null)
                                name = new Option<ExternalEvent1.NameEnum?>(ExternalEvent1.NameEnumFromStringOrDefault(nameRawValue));
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ExternalEvent1.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class ExternalEvent1.");

            return new ExternalEvent1(name, description);
        }

        /// <summary>
        /// Serializes a <see cref="ExternalEvent1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalEvent1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExternalEvent1 externalEvent1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, externalEvent1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExternalEvent1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalEvent1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExternalEvent1 externalEvent1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (externalEvent1.DescriptionOption.IsSet && externalEvent1.Description == null)
                throw new ArgumentNullException(nameof(externalEvent1.Description), "Property is required for class ExternalEvent1.");

            var nameRawValue = ExternalEvent1.NameEnumToJsonValue(externalEvent1.NameOption.Value!.Value);
            writer.WriteString("name", nameRawValue);
            if (externalEvent1.DescriptionOption.IsSet)
                writer.WriteString("description", externalEvent1.Description);
        }
    }
}
