// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// FailedStatusInfo
    /// </summary>
    public partial class FailedStatusInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FailedStatusInfo" /> class.
        /// </summary>
        /// <param name="errorDescription">Error description</param>
        /// <param name="errorCode">Error code</param>
        [JsonConstructor]
        public FailedStatusInfo(Option<string?> errorDescription = default, Option<string?> errorCode = default)
        {
            ErrorDescriptionOption = errorDescription;
            ErrorCodeOption = errorCode;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ErrorDescription
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorDescriptionOption { get; private set; }

        /// <summary>
        /// Error description
        /// </summary>
        /// <value>Error description</value>
        [JsonPropertyName("errorDescription")]
        public string? ErrorDescription { get { return this.ErrorDescriptionOption; } set { this.ErrorDescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ErrorCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorCodeOption { get; private set; }

        /// <summary>
        /// Error code
        /// </summary>
        /// <value>Error code</value>
        [JsonPropertyName("errorCode")]
        public string? ErrorCode { get { return this.ErrorCodeOption; } set { this.ErrorCodeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FailedStatusInfo {\n");
            sb.Append("  ErrorDescription: ").Append(ErrorDescription).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ErrorDescription (string) maxLength
            if (this.ErrorDescription != null && this.ErrorDescription.Length > 1000)
            {
                yield return new ValidationResult("Invalid value for ErrorDescription, length must be less than 1000.", new [] { "ErrorDescription" });
            }

            // ErrorCode (string) maxLength
            if (this.ErrorCode != null && this.ErrorCode.Length > 20)
            {
                yield return new ValidationResult("Invalid value for ErrorCode, length must be less than 20.", new [] { "ErrorCode" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FailedStatusInfo" />
    /// </summary>
    public class FailedStatusInfoJsonConverter : JsonConverter<FailedStatusInfo>
    {
        /// <summary>
        /// Deserializes json to <see cref="FailedStatusInfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FailedStatusInfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> errorDescription = default;
            Option<string?> errorCode = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "errorDescription":
                            errorDescription = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "errorCode":
                            errorCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (errorDescription.IsSet && errorDescription.Value == null)
                throw new ArgumentNullException(nameof(errorDescription), "Property is not nullable for class FailedStatusInfo.");

            if (errorCode.IsSet && errorCode.Value == null)
                throw new ArgumentNullException(nameof(errorCode), "Property is not nullable for class FailedStatusInfo.");

            return new FailedStatusInfo(errorDescription, errorCode);
        }

        /// <summary>
        /// Serializes a <see cref="FailedStatusInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="failedStatusInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FailedStatusInfo failedStatusInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, failedStatusInfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FailedStatusInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="failedStatusInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FailedStatusInfo failedStatusInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (failedStatusInfo.ErrorDescriptionOption.IsSet && failedStatusInfo.ErrorDescription == null)
                throw new ArgumentNullException(nameof(failedStatusInfo.ErrorDescription), "Property is required for class FailedStatusInfo.");

            if (failedStatusInfo.ErrorCodeOption.IsSet && failedStatusInfo.ErrorCode == null)
                throw new ArgumentNullException(nameof(failedStatusInfo.ErrorCode), "Property is required for class FailedStatusInfo.");

            if (failedStatusInfo.ErrorDescriptionOption.IsSet)
                writer.WriteString("errorDescription", failedStatusInfo.ErrorDescription);

            if (failedStatusInfo.ErrorCodeOption.IsSet)
                writer.WriteString("errorCode", failedStatusInfo.ErrorCode);
        }
    }
}
