// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetGiftCardRequest
    /// </summary>
    public partial class GetGiftCardRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetGiftCardRequest" /> class.
        /// </summary>
        /// <param name="giftCardId">The ID of the GiftCard to retrieve.</param>
        [JsonConstructor]
        public GetGiftCardRequest(Option<string?> giftCardId = default)
        {
            GiftCardIdOption = giftCardId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of GiftCardId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> GiftCardIdOption { get; private set; }

        /// <summary>
        /// The ID of the GiftCard to retrieve.
        /// </summary>
        /// <value>The ID of the GiftCard to retrieve.</value>
        [JsonPropertyName("giftCardId")]
        public string? GiftCardId { get { return this.GiftCardIdOption; } set { this.GiftCardIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetGiftCardRequest {\n");
            sb.Append("  GiftCardId: ").Append(GiftCardId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetGiftCardRequest" />
    /// </summary>
    public class GetGiftCardRequestJsonConverter : JsonConverter<GetGiftCardRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetGiftCardRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetGiftCardRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> giftCardId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "giftCardId":
                            giftCardId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (giftCardId.IsSet && giftCardId.Value == null)
                throw new ArgumentNullException(nameof(giftCardId), "Property is not nullable for class GetGiftCardRequest.");

            return new GetGiftCardRequest(giftCardId);
        }

        /// <summary>
        /// Serializes a <see cref="GetGiftCardRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getGiftCardRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetGiftCardRequest getGiftCardRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getGiftCardRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetGiftCardRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getGiftCardRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetGiftCardRequest getGiftCardRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getGiftCardRequest.GiftCardIdOption.IsSet && getGiftCardRequest.GiftCardId == null)
                throw new ArgumentNullException(nameof(getGiftCardRequest.GiftCardId), "Property is required for class GetGiftCardRequest.");

            if (getGiftCardRequest.GiftCardIdOption.IsSet)
                writer.WriteString("giftCardId", getGiftCardRequest.GiftCardId);
        }
    }
}
