// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetWalletGiftCardResponse
    /// </summary>
    public partial class GetWalletGiftCardResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWalletGiftCardResponse" /> class.
        /// </summary>
        /// <param name="giftCard">The retrieved Gift Card.</param>
        [JsonConstructor]
        public GetWalletGiftCardResponse(Option<Object?> giftCard = default)
        {
            GiftCardOption = giftCard;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of GiftCard
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> GiftCardOption { get; private set; }

        /// <summary>
        /// The retrieved Gift Card.
        /// </summary>
        /// <value>The retrieved Gift Card.</value>
        [JsonPropertyName("giftCard")]
        public Object? GiftCard { get { return this.GiftCardOption; } set { this.GiftCardOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetWalletGiftCardResponse {\n");
            sb.Append("  GiftCard: ").Append(GiftCard).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetWalletGiftCardResponse" />
    /// </summary>
    public class GetWalletGiftCardResponseJsonConverter : JsonConverter<GetWalletGiftCardResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetWalletGiftCardResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetWalletGiftCardResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Object?> giftCard = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "giftCard":
                            giftCard = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (giftCard.IsSet && giftCard.Value == null)
                throw new ArgumentNullException(nameof(giftCard), "Property is not nullable for class GetWalletGiftCardResponse.");

            return new GetWalletGiftCardResponse(giftCard);
        }

        /// <summary>
        /// Serializes a <see cref="GetWalletGiftCardResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getWalletGiftCardResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetWalletGiftCardResponse getWalletGiftCardResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getWalletGiftCardResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetWalletGiftCardResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getWalletGiftCardResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetWalletGiftCardResponse getWalletGiftCardResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getWalletGiftCardResponse.GiftCardOption.IsSet && getWalletGiftCardResponse.GiftCard == null)
                throw new ArgumentNullException(nameof(getWalletGiftCardResponse.GiftCard), "Property is required for class GetWalletGiftCardResponse.");

            if (getWalletGiftCardResponse.GiftCardOption.IsSet)
            {
                writer.WritePropertyName("giftCard");
                JsonSerializer.Serialize(writer, getWalletGiftCardResponse.GiftCard, jsonSerializerOptions);
            }
        }
    }
}
