// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetWalletActionRequest
    /// </summary>
    public partial class GetWalletActionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWalletActionRequest" /> class.
        /// </summary>
        /// <param name="walletActionId">ID of the WalletAction to retrieve.</param>
        [JsonConstructor]
        public GetWalletActionRequest(Option<string?> walletActionId = default)
        {
            WalletActionIdOption = walletActionId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of WalletActionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WalletActionIdOption { get; private set; }

        /// <summary>
        /// ID of the WalletAction to retrieve.
        /// </summary>
        /// <value>ID of the WalletAction to retrieve.</value>
        [JsonPropertyName("walletActionId")]
        public string? WalletActionId { get { return this.WalletActionIdOption; } set { this.WalletActionIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetWalletActionRequest {\n");
            sb.Append("  WalletActionId: ").Append(WalletActionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetWalletActionRequest" />
    /// </summary>
    public class GetWalletActionRequestJsonConverter : JsonConverter<GetWalletActionRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetWalletActionRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetWalletActionRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> walletActionId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "walletActionId":
                            walletActionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (walletActionId.IsSet && walletActionId.Value == null)
                throw new ArgumentNullException(nameof(walletActionId), "Property is not nullable for class GetWalletActionRequest.");

            return new GetWalletActionRequest(walletActionId);
        }

        /// <summary>
        /// Serializes a <see cref="GetWalletActionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getWalletActionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetWalletActionRequest getWalletActionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getWalletActionRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetWalletActionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getWalletActionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetWalletActionRequest getWalletActionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getWalletActionRequest.WalletActionIdOption.IsSet && getWalletActionRequest.WalletActionId == null)
                throw new ArgumentNullException(nameof(getWalletActionRequest.WalletActionId), "Property is required for class GetWalletActionRequest.");

            if (getWalletActionRequest.WalletActionIdOption.IsSet)
                writer.WriteString("walletActionId", getWalletActionRequest.WalletActionId);
        }
    }
}
