// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Information about the source of the gift card.
    /// </summary>
    public partial class GiftCardSourceInfo1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GiftCardSourceInfo1" /> class.
        /// </summary>
        /// <param name="orderOptions1"></param>
        /// <param name="type">The source type of the gift card.</param>
        /// <param name="sourceTenantId">The Tenant ID of the sales channel that is associated with the gift card creation (e.g. Shopify shop id).</param>
        /// <param name="sourceChannelId">The Channel ID of the sales channel that is associated with the gift card creation (e.g. Shopify channel id).</param>
        /// <param name="sourceLocationId">The location ID that is associated with the action (supports POS cases).</param>
        /// <param name="initiator">initiator</param>
        public GiftCardSourceInfo1(OrderOptions1 orderOptions1, Option<TypeEnum?> type = default, Option<string?> sourceTenantId = default, Option<string?> sourceChannelId = default, Option<string?> sourceLocationId = default, Option<ActionInitiator3?> initiator = default)
        {
            OrderOptions1 = orderOptions1;
            TypeOption = type;
            SourceTenantIdOption = sourceTenantId;
            SourceChannelIdOption = sourceChannelId;
            SourceLocationIdOption = sourceLocationId;
            InitiatorOption = initiator;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GiftCardSourceInfo1" /> class.
        /// </summary>
        /// <param name="campaignOptions2"></param>
        /// <param name="type">The source type of the gift card.</param>
        /// <param name="sourceTenantId">The Tenant ID of the sales channel that is associated with the gift card creation (e.g. Shopify shop id).</param>
        /// <param name="sourceChannelId">The Channel ID of the sales channel that is associated with the gift card creation (e.g. Shopify channel id).</param>
        /// <param name="sourceLocationId">The location ID that is associated with the action (supports POS cases).</param>
        /// <param name="initiator">initiator</param>
        public GiftCardSourceInfo1(CampaignOptions2 campaignOptions2, Option<TypeEnum?> type = default, Option<string?> sourceTenantId = default, Option<string?> sourceChannelId = default, Option<string?> sourceLocationId = default, Option<ActionInitiator3?> initiator = default)
        {
            CampaignOptions2 = campaignOptions2;
            TypeOption = type;
            SourceTenantIdOption = sourceTenantId;
            SourceChannelIdOption = sourceChannelId;
            SourceLocationIdOption = sourceLocationId;
            InitiatorOption = initiator;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GiftCardSourceInfo1" /> class.
        /// </summary>
        /// <param name="migrationOptions2"></param>
        /// <param name="type">The source type of the gift card.</param>
        /// <param name="sourceTenantId">The Tenant ID of the sales channel that is associated with the gift card creation (e.g. Shopify shop id).</param>
        /// <param name="sourceChannelId">The Channel ID of the sales channel that is associated with the gift card creation (e.g. Shopify channel id).</param>
        /// <param name="sourceLocationId">The location ID that is associated with the action (supports POS cases).</param>
        /// <param name="initiator">initiator</param>
        public GiftCardSourceInfo1(MigrationOptions2 migrationOptions2, Option<TypeEnum?> type = default, Option<string?> sourceTenantId = default, Option<string?> sourceChannelId = default, Option<string?> sourceLocationId = default, Option<ActionInitiator3?> initiator = default)
        {
            MigrationOptions2 = migrationOptions2;
            TypeOption = type;
            SourceTenantIdOption = sourceTenantId;
            SourceChannelIdOption = sourceChannelId;
            SourceLocationIdOption = sourceLocationId;
            InitiatorOption = initiator;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GiftCardSourceInfo1" /> class.
        /// </summary>
        /// <param name="storeCreditOptions1"></param>
        /// <param name="type">The source type of the gift card.</param>
        /// <param name="sourceTenantId">The Tenant ID of the sales channel that is associated with the gift card creation (e.g. Shopify shop id).</param>
        /// <param name="sourceChannelId">The Channel ID of the sales channel that is associated with the gift card creation (e.g. Shopify channel id).</param>
        /// <param name="sourceLocationId">The location ID that is associated with the action (supports POS cases).</param>
        /// <param name="initiator">initiator</param>
        public GiftCardSourceInfo1(StoreCreditOptions1 storeCreditOptions1, Option<TypeEnum?> type = default, Option<string?> sourceTenantId = default, Option<string?> sourceChannelId = default, Option<string?> sourceLocationId = default, Option<ActionInitiator3?> initiator = default)
        {
            StoreCreditOptions1 = storeCreditOptions1;
            TypeOption = type;
            SourceTenantIdOption = sourceTenantId;
            SourceChannelIdOption = sourceChannelId;
            SourceLocationIdOption = sourceLocationId;
            InitiatorOption = initiator;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GiftCardSourceInfo1" /> class.
        /// </summary>
        /// <param name="workflowOptions1"></param>
        /// <param name="type">The source type of the gift card.</param>
        /// <param name="sourceTenantId">The Tenant ID of the sales channel that is associated with the gift card creation (e.g. Shopify shop id).</param>
        /// <param name="sourceChannelId">The Channel ID of the sales channel that is associated with the gift card creation (e.g. Shopify channel id).</param>
        /// <param name="sourceLocationId">The location ID that is associated with the action (supports POS cases).</param>
        /// <param name="initiator">initiator</param>
        public GiftCardSourceInfo1(WorkflowOptions1 workflowOptions1, Option<TypeEnum?> type = default, Option<string?> sourceTenantId = default, Option<string?> sourceChannelId = default, Option<string?> sourceLocationId = default, Option<ActionInitiator3?> initiator = default)
        {
            WorkflowOptions1 = workflowOptions1;
            TypeOption = type;
            SourceTenantIdOption = sourceTenantId;
            SourceChannelIdOption = sourceChannelId;
            SourceLocationIdOption = sourceLocationId;
            InitiatorOption = initiator;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GiftCardSourceInfo1" /> class.
        /// </summary>
        /// <param name="bulkOptions2"></param>
        /// <param name="type">The source type of the gift card.</param>
        /// <param name="sourceTenantId">The Tenant ID of the sales channel that is associated with the gift card creation (e.g. Shopify shop id).</param>
        /// <param name="sourceChannelId">The Channel ID of the sales channel that is associated with the gift card creation (e.g. Shopify channel id).</param>
        /// <param name="sourceLocationId">The location ID that is associated with the action (supports POS cases).</param>
        /// <param name="initiator">initiator</param>
        public GiftCardSourceInfo1(BulkOptions2 bulkOptions2, Option<TypeEnum?> type = default, Option<string?> sourceTenantId = default, Option<string?> sourceChannelId = default, Option<string?> sourceLocationId = default, Option<ActionInitiator3?> initiator = default)
        {
            BulkOptions2 = bulkOptions2;
            TypeOption = type;
            SourceTenantIdOption = sourceTenantId;
            SourceChannelIdOption = sourceChannelId;
            SourceLocationIdOption = sourceLocationId;
            InitiatorOption = initiator;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GiftCardSourceInfo1" /> class.
        /// </summary>
        /// <param name="manualOptions2"></param>
        /// <param name="type">The source type of the gift card.</param>
        /// <param name="sourceTenantId">The Tenant ID of the sales channel that is associated with the gift card creation (e.g. Shopify shop id).</param>
        /// <param name="sourceChannelId">The Channel ID of the sales channel that is associated with the gift card creation (e.g. Shopify channel id).</param>
        /// <param name="sourceLocationId">The location ID that is associated with the action (supports POS cases).</param>
        /// <param name="initiator">initiator</param>
        public GiftCardSourceInfo1(ManualOptions2 manualOptions2, Option<TypeEnum?> type = default, Option<string?> sourceTenantId = default, Option<string?> sourceChannelId = default, Option<string?> sourceLocationId = default, Option<ActionInitiator3?> initiator = default)
        {
            ManualOptions2 = manualOptions2;
            TypeOption = type;
            SourceTenantIdOption = sourceTenantId;
            SourceChannelIdOption = sourceChannelId;
            SourceLocationIdOption = sourceLocationId;
            InitiatorOption = initiator;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The source type of the gift card.
        /// </summary>
        /// <value>The source type of the gift card.</value>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Order1valueORDERdescriptionIssuedFromAnOrdermaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:1,\&quot;value\&quot;:\&quot;ORDER\&quot;,\&quot;description\&quot;:\&quot;Issued from an order.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order1valueORDERdescriptionIssuedFromAnOrdermaturityGAexposurePUBLIC = 1,

            /// <summary>
            /// Enum Order2valueCAMPAIGNdescriptionmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:2,\&quot;value\&quot;:\&quot;CAMPAIGN\&quot;,\&quot;description\&quot;:\&quot;\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order2valueCAMPAIGNdescriptionmaturityGAexposurePUBLIC = 2,

            /// <summary>
            /// Enum Order3valueMIGRATIONdescriptionMigratedFromRiseV1OrAnotherPlatformmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:3,\&quot;value\&quot;:\&quot;MIGRATION\&quot;,\&quot;description\&quot;:\&quot;Migrated from Rise V1 or another platform.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order3valueMIGRATIONdescriptionMigratedFromRiseV1OrAnotherPlatformmaturityGAexposurePUBLIC = 3,

            /// <summary>
            /// Enum Order4valueSTORECREDITdescriptionBelongsToAStoreCreditWalletmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:4,\&quot;value\&quot;:\&quot;STORE_CREDIT\&quot;,\&quot;description\&quot;:\&quot;Belongs to a Store Credit Wallet.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order4valueSTORECREDITdescriptionBelongsToAStoreCreditWalletmaturityGAexposurePUBLIC = 4,

            /// <summary>
            /// Enum Order5valueMANUALdescriptionIssuedFromTheDashboardmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:5,\&quot;value\&quot;:\&quot;MANUAL\&quot;,\&quot;description\&quot;:\&quot;Issued from the dashboard.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order5valueMANUALdescriptionIssuedFromTheDashboardmaturityGAexposurePUBLIC = 5,

            /// <summary>
            /// Enum Order6valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:6,\&quot;value\&quot;:\&quot;WORKFLOW\&quot;,\&quot;description\&quot;:\&quot;Issued from a workflow.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order6valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC = 6,

            /// <summary>
            /// Enum Order7valueBULKdescriptionIssuedFromABulkOperationmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:7,\&quot;value\&quot;:\&quot;BULK\&quot;,\&quot;description\&quot;:\&quot;Issued from a bulk operation.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order7valueBULKdescriptionIssuedFromABulkOperationmaturityGAexposurePUBLIC = 7
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("{\"order\":1,\"value\":\"ORDER\",\"description\":\"Issued from an order.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order1valueORDERdescriptionIssuedFromAnOrdermaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":2,\"value\":\"CAMPAIGN\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order2valueCAMPAIGNdescriptionmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":3,\"value\":\"MIGRATION\",\"description\":\"Migrated from Rise V1 or another platform.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order3valueMIGRATIONdescriptionMigratedFromRiseV1OrAnotherPlatformmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":4,\"value\":\"STORE_CREDIT\",\"description\":\"Belongs to a Store Credit Wallet.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order4valueSTORECREDITdescriptionBelongsToAStoreCreditWalletmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":5,\"value\":\"MANUAL\",\"description\":\"Issued from the dashboard.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order5valueMANUALdescriptionIssuedFromTheDashboardmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":6,\"value\":\"WORKFLOW\",\"description\":\"Issued from a workflow.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order6valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":7,\"value\":\"BULK\",\"description\":\"Issued from a bulk operation.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order7valueBULKdescriptionIssuedFromABulkOperationmaturityGAexposurePUBLIC;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("{\"order\":1,\"value\":\"ORDER\",\"description\":\"Issued from an order.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order1valueORDERdescriptionIssuedFromAnOrdermaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":2,\"value\":\"CAMPAIGN\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order2valueCAMPAIGNdescriptionmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":3,\"value\":\"MIGRATION\",\"description\":\"Migrated from Rise V1 or another platform.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order3valueMIGRATIONdescriptionMigratedFromRiseV1OrAnotherPlatformmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":4,\"value\":\"STORE_CREDIT\",\"description\":\"Belongs to a Store Credit Wallet.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order4valueSTORECREDITdescriptionBelongsToAStoreCreditWalletmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":5,\"value\":\"MANUAL\",\"description\":\"Issued from the dashboard.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order5valueMANUALdescriptionIssuedFromTheDashboardmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":6,\"value\":\"WORKFLOW\",\"description\":\"Issued from a workflow.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order6valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":7,\"value\":\"BULK\",\"description\":\"Issued from a bulk operation.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return TypeEnum.Order7valueBULKdescriptionIssuedFromABulkOperationmaturityGAexposurePUBLIC;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum? value)
        {
            if (value == TypeEnum.Order1valueORDERdescriptionIssuedFromAnOrdermaturityGAexposurePUBLIC)
                return "{\"order\":1,\"value\":\"ORDER\",\"description\":\"Issued from an order.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == TypeEnum.Order2valueCAMPAIGNdescriptionmaturityGAexposurePUBLIC)
                return "{\"order\":2,\"value\":\"CAMPAIGN\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == TypeEnum.Order3valueMIGRATIONdescriptionMigratedFromRiseV1OrAnotherPlatformmaturityGAexposurePUBLIC)
                return "{\"order\":3,\"value\":\"MIGRATION\",\"description\":\"Migrated from Rise V1 or another platform.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == TypeEnum.Order4valueSTORECREDITdescriptionBelongsToAStoreCreditWalletmaturityGAexposurePUBLIC)
                return "{\"order\":4,\"value\":\"STORE_CREDIT\",\"description\":\"Belongs to a Store Credit Wallet.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == TypeEnum.Order5valueMANUALdescriptionIssuedFromTheDashboardmaturityGAexposurePUBLIC)
                return "{\"order\":5,\"value\":\"MANUAL\",\"description\":\"Issued from the dashboard.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == TypeEnum.Order6valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC)
                return "{\"order\":6,\"value\":\"WORKFLOW\",\"description\":\"Issued from a workflow.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == TypeEnum.Order7valueBULKdescriptionIssuedFromABulkOperationmaturityGAexposurePUBLIC)
                return "{\"order\":7,\"value\":\"BULK\",\"description\":\"Issued from a bulk operation.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TypeEnum?> TypeOption { get; private set; }

        /// <summary>
        /// The source type of the gift card.
        /// </summary>
        /// <value>The source type of the gift card.</value>
        [JsonPropertyName("type")]
        public TypeEnum? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Gets or Sets OrderOptions1
        /// </summary>
        public OrderOptions1? OrderOptions1 { get; set; }

        /// <summary>
        /// Gets or Sets CampaignOptions2
        /// </summary>
        public CampaignOptions2? CampaignOptions2 { get; set; }

        /// <summary>
        /// Gets or Sets MigrationOptions2
        /// </summary>
        public MigrationOptions2? MigrationOptions2 { get; set; }

        /// <summary>
        /// Gets or Sets StoreCreditOptions1
        /// </summary>
        public StoreCreditOptions1? StoreCreditOptions1 { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowOptions1
        /// </summary>
        public WorkflowOptions1? WorkflowOptions1 { get; set; }

        /// <summary>
        /// Gets or Sets BulkOptions2
        /// </summary>
        public BulkOptions2? BulkOptions2 { get; set; }

        /// <summary>
        /// Gets or Sets ManualOptions2
        /// </summary>
        public ManualOptions2? ManualOptions2 { get; set; }

        /// <summary>
        /// Used to track the state of SourceTenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceTenantIdOption { get; private set; }

        /// <summary>
        /// The Tenant ID of the sales channel that is associated with the gift card creation (e.g. Shopify shop id).
        /// </summary>
        /// <value>The Tenant ID of the sales channel that is associated with the gift card creation (e.g. Shopify shop id).</value>
        [JsonPropertyName("sourceTenantId")]
        public string? SourceTenantId { get { return this.SourceTenantIdOption; } set { this.SourceTenantIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceChannelId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceChannelIdOption { get; private set; }

        /// <summary>
        /// The Channel ID of the sales channel that is associated with the gift card creation (e.g. Shopify channel id).
        /// </summary>
        /// <value>The Channel ID of the sales channel that is associated with the gift card creation (e.g. Shopify channel id).</value>
        [JsonPropertyName("sourceChannelId")]
        public string? SourceChannelId { get { return this.SourceChannelIdOption; } set { this.SourceChannelIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceLocationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceLocationIdOption { get; private set; }

        /// <summary>
        /// The location ID that is associated with the action (supports POS cases).
        /// </summary>
        /// <value>The location ID that is associated with the action (supports POS cases).</value>
        [JsonPropertyName("sourceLocationId")]
        public string? SourceLocationId { get { return this.SourceLocationIdOption; } set { this.SourceLocationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Initiator
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ActionInitiator3?> InitiatorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Initiator
        /// </summary>
        [JsonPropertyName("initiator")]
        public ActionInitiator3? Initiator { get { return this.InitiatorOption; } set { this.InitiatorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GiftCardSourceInfo1 {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  SourceTenantId: ").Append(SourceTenantId).Append("\n");
            sb.Append("  SourceChannelId: ").Append(SourceChannelId).Append("\n");
            sb.Append("  SourceLocationId: ").Append(SourceLocationId).Append("\n");
            sb.Append("  Initiator: ").Append(Initiator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SourceTenantId (string) maxLength
            if (this.SourceTenantId != null && this.SourceTenantId.Length > 50)
            {
                yield return new ValidationResult("Invalid value for SourceTenantId, length must be less than 50.", new [] { "SourceTenantId" });
            }

            // SourceTenantId (string) minLength
            if (this.SourceTenantId != null && this.SourceTenantId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for SourceTenantId, length must be greater than 1.", new [] { "SourceTenantId" });
            }

            // SourceLocationId (string) maxLength
            if (this.SourceLocationId != null && this.SourceLocationId.Length > 50)
            {
                yield return new ValidationResult("Invalid value for SourceLocationId, length must be less than 50.", new [] { "SourceLocationId" });
            }

            // SourceLocationId (string) minLength
            if (this.SourceLocationId != null && this.SourceLocationId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for SourceLocationId, length must be greater than 1.", new [] { "SourceLocationId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GiftCardSourceInfo1" />
    /// </summary>
    public class GiftCardSourceInfo1JsonConverter : JsonConverter<GiftCardSourceInfo1>
    {
        /// <summary>
        /// Deserializes json to <see cref="GiftCardSourceInfo1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GiftCardSourceInfo1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<GiftCardSourceInfo1.TypeEnum?> type = default;
            Option<string?> sourceTenantId = default;
            Option<string?> sourceChannelId = default;
            Option<string?> sourceLocationId = default;
            Option<ActionInitiator3?> initiator = default;

            OrderOptions1? orderOptions1 = default;
            CampaignOptions2? campaignOptions2 = default;
            MigrationOptions2? migrationOptions2 = default;
            StoreCreditOptions1? storeCreditOptions1 = default;
            WorkflowOptions1? workflowOptions1 = default;
            BulkOptions2? bulkOptions2 = default;
            ManualOptions2? manualOptions2 = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderOrderOptions1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<OrderOptions1?>(ref utf8JsonReaderOrderOptions1, jsonSerializerOptions, out orderOptions1);

                    Utf8JsonReader utf8JsonReaderCampaignOptions2 = utf8JsonReader;
                    ClientUtils.TryDeserialize<CampaignOptions2?>(ref utf8JsonReaderCampaignOptions2, jsonSerializerOptions, out campaignOptions2);

                    Utf8JsonReader utf8JsonReaderMigrationOptions2 = utf8JsonReader;
                    ClientUtils.TryDeserialize<MigrationOptions2?>(ref utf8JsonReaderMigrationOptions2, jsonSerializerOptions, out migrationOptions2);

                    Utf8JsonReader utf8JsonReaderStoreCreditOptions1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<StoreCreditOptions1?>(ref utf8JsonReaderStoreCreditOptions1, jsonSerializerOptions, out storeCreditOptions1);

                    Utf8JsonReader utf8JsonReaderWorkflowOptions1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<WorkflowOptions1?>(ref utf8JsonReaderWorkflowOptions1, jsonSerializerOptions, out workflowOptions1);

                    Utf8JsonReader utf8JsonReaderBulkOptions2 = utf8JsonReader;
                    ClientUtils.TryDeserialize<BulkOptions2?>(ref utf8JsonReaderBulkOptions2, jsonSerializerOptions, out bulkOptions2);

                    Utf8JsonReader utf8JsonReaderManualOptions2 = utf8JsonReader;
                    ClientUtils.TryDeserialize<ManualOptions2?>(ref utf8JsonReaderManualOptions2, jsonSerializerOptions, out manualOptions2);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<GiftCardSourceInfo1.TypeEnum?>(GiftCardSourceInfo1.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "sourceTenantId":
                            sourceTenantId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceChannelId":
                            sourceChannelId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceLocationId":
                            sourceLocationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "initiator":
                            initiator = new Option<ActionInitiator3?>(JsonSerializer.Deserialize<ActionInitiator3>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class GiftCardSourceInfo1.");

            if (sourceTenantId.IsSet && sourceTenantId.Value == null)
                throw new ArgumentNullException(nameof(sourceTenantId), "Property is not nullable for class GiftCardSourceInfo1.");

            if (sourceChannelId.IsSet && sourceChannelId.Value == null)
                throw new ArgumentNullException(nameof(sourceChannelId), "Property is not nullable for class GiftCardSourceInfo1.");

            if (sourceLocationId.IsSet && sourceLocationId.Value == null)
                throw new ArgumentNullException(nameof(sourceLocationId), "Property is not nullable for class GiftCardSourceInfo1.");

            if (initiator.IsSet && initiator.Value == null)
                throw new ArgumentNullException(nameof(initiator), "Property is not nullable for class GiftCardSourceInfo1.");

            if (orderOptions1 != null)
                return new GiftCardSourceInfo1(orderOptions1, type, sourceTenantId, sourceChannelId, sourceLocationId, initiator);

            if (campaignOptions2 != null)
                return new GiftCardSourceInfo1(campaignOptions2, type, sourceTenantId, sourceChannelId, sourceLocationId, initiator);

            if (migrationOptions2 != null)
                return new GiftCardSourceInfo1(migrationOptions2, type, sourceTenantId, sourceChannelId, sourceLocationId, initiator);

            if (storeCreditOptions1 != null)
                return new GiftCardSourceInfo1(storeCreditOptions1, type, sourceTenantId, sourceChannelId, sourceLocationId, initiator);

            if (workflowOptions1 != null)
                return new GiftCardSourceInfo1(workflowOptions1, type, sourceTenantId, sourceChannelId, sourceLocationId, initiator);

            if (bulkOptions2 != null)
                return new GiftCardSourceInfo1(bulkOptions2, type, sourceTenantId, sourceChannelId, sourceLocationId, initiator);

            if (manualOptions2 != null)
                return new GiftCardSourceInfo1(manualOptions2, type, sourceTenantId, sourceChannelId, sourceLocationId, initiator);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="GiftCardSourceInfo1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="giftCardSourceInfo1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GiftCardSourceInfo1 giftCardSourceInfo1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, giftCardSourceInfo1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GiftCardSourceInfo1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="giftCardSourceInfo1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GiftCardSourceInfo1 giftCardSourceInfo1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (giftCardSourceInfo1.SourceTenantIdOption.IsSet && giftCardSourceInfo1.SourceTenantId == null)
                throw new ArgumentNullException(nameof(giftCardSourceInfo1.SourceTenantId), "Property is required for class GiftCardSourceInfo1.");

            if (giftCardSourceInfo1.SourceChannelIdOption.IsSet && giftCardSourceInfo1.SourceChannelId == null)
                throw new ArgumentNullException(nameof(giftCardSourceInfo1.SourceChannelId), "Property is required for class GiftCardSourceInfo1.");

            if (giftCardSourceInfo1.SourceLocationIdOption.IsSet && giftCardSourceInfo1.SourceLocationId == null)
                throw new ArgumentNullException(nameof(giftCardSourceInfo1.SourceLocationId), "Property is required for class GiftCardSourceInfo1.");

            if (giftCardSourceInfo1.InitiatorOption.IsSet && giftCardSourceInfo1.Initiator == null)
                throw new ArgumentNullException(nameof(giftCardSourceInfo1.Initiator), "Property is required for class GiftCardSourceInfo1.");

            var typeRawValue = GiftCardSourceInfo1.TypeEnumToJsonValue(giftCardSourceInfo1.TypeOption.Value!.Value);
            writer.WriteString("type", typeRawValue);
            if (giftCardSourceInfo1.SourceTenantIdOption.IsSet)
                writer.WriteString("sourceTenantId", giftCardSourceInfo1.SourceTenantId);

            if (giftCardSourceInfo1.SourceChannelIdOption.IsSet)
                writer.WriteString("sourceChannelId", giftCardSourceInfo1.SourceChannelId);

            if (giftCardSourceInfo1.SourceLocationIdOption.IsSet)
                writer.WriteString("sourceLocationId", giftCardSourceInfo1.SourceLocationId);

            if (giftCardSourceInfo1.InitiatorOption.IsSet)
            {
                writer.WritePropertyName("initiator");
                JsonSerializer.Serialize(writer, giftCardSourceInfo1.Initiator, jsonSerializerOptions);
            }
        }
    }
}
