// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InitiatedStatusInfo
    /// </summary>
    public partial class InitiatedStatusInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InitiatedStatusInfo" /> class.
        /// </summary>
        /// <param name="target">Activation target</param>
        /// <param name="payload">Event payload</param>
        /// <param name="externalEntityId">External entity ID</param>
        /// <param name="requestId">Unique identifier for the request that initiated the automation</param>
        [JsonConstructor]
        public InitiatedStatusInfo(Option<string?> target = default, Option<Object?> payload = default, Option<string?> externalEntityId = default, Option<string?> requestId = default)
        {
            TargetOption = target;
            PayloadOption = payload;
            ExternalEntityIdOption = externalEntityId;
            RequestIdOption = requestId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Target
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TargetOption { get; private set; }

        /// <summary>
        /// Activation target
        /// </summary>
        /// <value>Activation target</value>
        [JsonPropertyName("target")]
        public string? Target { get { return this.TargetOption; } set { this.TargetOption = new(value); } }

        /// <summary>
        /// Used to track the state of Payload
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> PayloadOption { get; private set; }

        /// <summary>
        /// Event payload
        /// </summary>
        /// <value>Event payload</value>
        [JsonPropertyName("payload")]
        public Object? Payload { get { return this.PayloadOption; } set { this.PayloadOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalEntityId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalEntityIdOption { get; private set; }

        /// <summary>
        /// External entity ID
        /// </summary>
        /// <value>External entity ID</value>
        [JsonPropertyName("externalEntityId")]
        public string? ExternalEntityId { get { return this.ExternalEntityIdOption; } set { this.ExternalEntityIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequestId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RequestIdOption { get; private set; }

        /// <summary>
        /// Unique identifier for the request that initiated the automation
        /// </summary>
        /// <value>Unique identifier for the request that initiated the automation</value>
        [JsonPropertyName("requestId")]
        public string? RequestId { get { return this.RequestIdOption; } set { this.RequestIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InitiatedStatusInfo {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  ExternalEntityId: ").Append(ExternalEntityId).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ExternalEntityId (string) maxLength
            if (this.ExternalEntityId != null && this.ExternalEntityId.Length > 40)
            {
                yield return new ValidationResult("Invalid value for ExternalEntityId, length must be less than 40.", new [] { "ExternalEntityId" });
            }

            // RequestId (string) maxLength
            if (this.RequestId != null && this.RequestId.Length > 100)
            {
                yield return new ValidationResult("Invalid value for RequestId, length must be less than 100.", new [] { "RequestId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InitiatedStatusInfo" />
    /// </summary>
    public class InitiatedStatusInfoJsonConverter : JsonConverter<InitiatedStatusInfo>
    {
        /// <summary>
        /// Deserializes json to <see cref="InitiatedStatusInfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InitiatedStatusInfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> target = default;
            Option<Object?> payload = default;
            Option<string?> externalEntityId = default;
            Option<string?> requestId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "target":
                            target = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "payload":
                            payload = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "externalEntityId":
                            externalEntityId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "requestId":
                            requestId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (target.IsSet && target.Value == null)
                throw new ArgumentNullException(nameof(target), "Property is not nullable for class InitiatedStatusInfo.");

            if (payload.IsSet && payload.Value == null)
                throw new ArgumentNullException(nameof(payload), "Property is not nullable for class InitiatedStatusInfo.");

            if (externalEntityId.IsSet && externalEntityId.Value == null)
                throw new ArgumentNullException(nameof(externalEntityId), "Property is not nullable for class InitiatedStatusInfo.");

            if (requestId.IsSet && requestId.Value == null)
                throw new ArgumentNullException(nameof(requestId), "Property is not nullable for class InitiatedStatusInfo.");

            return new InitiatedStatusInfo(target, payload, externalEntityId, requestId);
        }

        /// <summary>
        /// Serializes a <see cref="InitiatedStatusInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="initiatedStatusInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InitiatedStatusInfo initiatedStatusInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, initiatedStatusInfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InitiatedStatusInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="initiatedStatusInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InitiatedStatusInfo initiatedStatusInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (initiatedStatusInfo.TargetOption.IsSet && initiatedStatusInfo.Target == null)
                throw new ArgumentNullException(nameof(initiatedStatusInfo.Target), "Property is required for class InitiatedStatusInfo.");

            if (initiatedStatusInfo.PayloadOption.IsSet && initiatedStatusInfo.Payload == null)
                throw new ArgumentNullException(nameof(initiatedStatusInfo.Payload), "Property is required for class InitiatedStatusInfo.");

            if (initiatedStatusInfo.ExternalEntityIdOption.IsSet && initiatedStatusInfo.ExternalEntityId == null)
                throw new ArgumentNullException(nameof(initiatedStatusInfo.ExternalEntityId), "Property is required for class InitiatedStatusInfo.");

            if (initiatedStatusInfo.RequestIdOption.IsSet && initiatedStatusInfo.RequestId == null)
                throw new ArgumentNullException(nameof(initiatedStatusInfo.RequestId), "Property is required for class InitiatedStatusInfo.");

            if (initiatedStatusInfo.TargetOption.IsSet)
                writer.WriteString("target", initiatedStatusInfo.Target);

            if (initiatedStatusInfo.PayloadOption.IsSet)
            {
                writer.WritePropertyName("payload");
                JsonSerializer.Serialize(writer, initiatedStatusInfo.Payload, jsonSerializerOptions);
            }
            if (initiatedStatusInfo.ExternalEntityIdOption.IsSet)
                writer.WriteString("externalEntityId", initiatedStatusInfo.ExternalEntityId);

            if (initiatedStatusInfo.RequestIdOption.IsSet)
                writer.WriteString("requestId", initiatedStatusInfo.RequestId);
        }
    }
}
