// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// INVALIDGIFTCARDBALANCE
    /// </summary>
    public partial class INVALIDGIFTCARDBALANCE : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="INVALIDGIFTCARDBALANCE" /> class.
        /// </summary>
        /// <param name="message">Error message</param>
        /// <param name="details">details</param>
        [JsonConstructor]
        public INVALIDGIFTCARDBALANCE(string message, INVALIDGIFTCARDBALANCEDetails details)
        {
            Message = message;
            Details = details;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Error message
        /// </summary>
        /// <value>Error message</value>
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [JsonPropertyName("details")]
        public INVALIDGIFTCARDBALANCEDetails Details { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class INVALIDGIFTCARDBALANCE {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="INVALIDGIFTCARDBALANCE" />
    /// </summary>
    public class INVALIDGIFTCARDBALANCEJsonConverter : JsonConverter<INVALIDGIFTCARDBALANCE>
    {
        /// <summary>
        /// Deserializes json to <see cref="INVALIDGIFTCARDBALANCE" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override INVALIDGIFTCARDBALANCE Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> message = default;
            Option<INVALIDGIFTCARDBALANCEDetails?> details = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "details":
                            details = new Option<INVALIDGIFTCARDBALANCEDetails?>(JsonSerializer.Deserialize<INVALIDGIFTCARDBALANCEDetails>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class INVALIDGIFTCARDBALANCE.", nameof(message));

            if (!details.IsSet)
                throw new ArgumentException("Property is required for class INVALIDGIFTCARDBALANCE.", nameof(details));

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class INVALIDGIFTCARDBALANCE.");

            if (details.IsSet && details.Value == null)
                throw new ArgumentNullException(nameof(details), "Property is not nullable for class INVALIDGIFTCARDBALANCE.");

            return new INVALIDGIFTCARDBALANCE(message.Value!, details.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="INVALIDGIFTCARDBALANCE" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="iNVALIDGIFTCARDBALANCE"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, INVALIDGIFTCARDBALANCE iNVALIDGIFTCARDBALANCE, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, iNVALIDGIFTCARDBALANCE, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="INVALIDGIFTCARDBALANCE" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="iNVALIDGIFTCARDBALANCE"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, INVALIDGIFTCARDBALANCE iNVALIDGIFTCARDBALANCE, JsonSerializerOptions jsonSerializerOptions)
        {
            if (iNVALIDGIFTCARDBALANCE.Message == null)
                throw new ArgumentNullException(nameof(iNVALIDGIFTCARDBALANCE.Message), "Property is required for class INVALIDGIFTCARDBALANCE.");

            if (iNVALIDGIFTCARDBALANCE.Details == null)
                throw new ArgumentNullException(nameof(iNVALIDGIFTCARDBALANCE.Details), "Property is required for class INVALIDGIFTCARDBALANCE.");

            writer.WriteString("message", iNVALIDGIFTCARDBALANCE.Message);

            writer.WritePropertyName("details");
            JsonSerializer.Serialize(writer, iNVALIDGIFTCARDBALANCE.Details, jsonSerializerOptions);
        }
    }
}
