// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PagingMethod
    /// </summary>
    public partial class PagingMethod : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PagingMethod" /> class.
        /// </summary>
        /// <param name="paging">Paging options to limit and skip the number of items.</param>
        /// <param name="cursorPaging">Cursor token pointing to a page of results. Not used in the first request. Following requests use the cursor token and not &#x60;filter&#x60; or &#x60;sort&#x60;.</param>
        [JsonConstructor]
        public PagingMethod(Option<Object?> paging = default, Option<Object?> cursorPaging = default)
        {
            PagingOption = paging;
            CursorPagingOption = cursorPaging;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Paging
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> PagingOption { get; private set; }

        /// <summary>
        /// Paging options to limit and skip the number of items.
        /// </summary>
        /// <value>Paging options to limit and skip the number of items.</value>
        [JsonPropertyName("paging")]
        public Object? Paging { get { return this.PagingOption; } set { this.PagingOption = new(value); } }

        /// <summary>
        /// Used to track the state of CursorPaging
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> CursorPagingOption { get; private set; }

        /// <summary>
        /// Cursor token pointing to a page of results. Not used in the first request. Following requests use the cursor token and not &#x60;filter&#x60; or &#x60;sort&#x60;.
        /// </summary>
        /// <value>Cursor token pointing to a page of results. Not used in the first request. Following requests use the cursor token and not &#x60;filter&#x60; or &#x60;sort&#x60;.</value>
        [JsonPropertyName("cursorPaging")]
        public Object? CursorPaging { get { return this.CursorPagingOption; } set { this.CursorPagingOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PagingMethod {\n");
            sb.Append("  Paging: ").Append(Paging).Append("\n");
            sb.Append("  CursorPaging: ").Append(CursorPaging).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PagingMethod" />
    /// </summary>
    public class PagingMethodJsonConverter : JsonConverter<PagingMethod>
    {
        /// <summary>
        /// Deserializes json to <see cref="PagingMethod" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PagingMethod Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Object?> paging = default;
            Option<Object?> cursorPaging = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "paging":
                            paging = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "cursorPaging":
                            cursorPaging = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (paging.IsSet && paging.Value == null)
                throw new ArgumentNullException(nameof(paging), "Property is not nullable for class PagingMethod.");

            if (cursorPaging.IsSet && cursorPaging.Value == null)
                throw new ArgumentNullException(nameof(cursorPaging), "Property is not nullable for class PagingMethod.");

            return new PagingMethod(paging, cursorPaging);
        }

        /// <summary>
        /// Serializes a <see cref="PagingMethod" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pagingMethod"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PagingMethod pagingMethod, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pagingMethod, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PagingMethod" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pagingMethod"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PagingMethod pagingMethod, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pagingMethod.PagingOption.IsSet && pagingMethod.Paging == null)
                throw new ArgumentNullException(nameof(pagingMethod.Paging), "Property is required for class PagingMethod.");

            if (pagingMethod.CursorPagingOption.IsSet && pagingMethod.CursorPaging == null)
                throw new ArgumentNullException(nameof(pagingMethod.CursorPaging), "Property is required for class PagingMethod.");

            if (pagingMethod.PagingOption.IsSet)
            {
                writer.WritePropertyName("paging");
                JsonSerializer.Serialize(writer, pagingMethod.Paging, jsonSerializerOptions);
            }
            if (pagingMethod.CursorPagingOption.IsSet)
            {
                writer.WritePropertyName("cursorPaging");
                JsonSerializer.Serialize(writer, pagingMethod.CursorPaging, jsonSerializerOptions);
            }
        }
    }
}
