// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RefundTransactionContext
    /// </summary>
    public partial class RefundTransactionContext : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundTransactionContext" /> class.
        /// </summary>
        /// <param name="sourceTenantId">sourceTenantId</param>
        /// <param name="sourceChannelId">sourceChannelId</param>
        /// <param name="sourceLocationId">sourceLocationId</param>
        /// <param name="sourceOrderId">sourceOrderId</param>
        /// <param name="sourceOrderNumber">sourceOrderNumber</param>
        [JsonConstructor]
        public RefundTransactionContext(Option<string?> sourceTenantId = default, Option<string?> sourceChannelId = default, Option<string?> sourceLocationId = default, Option<string?> sourceOrderId = default, Option<string?> sourceOrderNumber = default)
        {
            SourceTenantIdOption = sourceTenantId;
            SourceChannelIdOption = sourceChannelId;
            SourceLocationIdOption = sourceLocationId;
            SourceOrderIdOption = sourceOrderId;
            SourceOrderNumberOption = sourceOrderNumber;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SourceTenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceTenantIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SourceTenantId
        /// </summary>
        [JsonPropertyName("sourceTenantId")]
        public string? SourceTenantId { get { return this.SourceTenantIdOption; } set { this.SourceTenantIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceChannelId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceChannelIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SourceChannelId
        /// </summary>
        [JsonPropertyName("sourceChannelId")]
        public string? SourceChannelId { get { return this.SourceChannelIdOption; } set { this.SourceChannelIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceLocationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceLocationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SourceLocationId
        /// </summary>
        [JsonPropertyName("sourceLocationId")]
        public string? SourceLocationId { get { return this.SourceLocationIdOption; } set { this.SourceLocationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceOrderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceOrderIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SourceOrderId
        /// </summary>
        [JsonPropertyName("sourceOrderId")]
        public string? SourceOrderId { get { return this.SourceOrderIdOption; } set { this.SourceOrderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceOrderNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceOrderNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets SourceOrderNumber
        /// </summary>
        [JsonPropertyName("sourceOrderNumber")]
        public string? SourceOrderNumber { get { return this.SourceOrderNumberOption; } set { this.SourceOrderNumberOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RefundTransactionContext {\n");
            sb.Append("  SourceTenantId: ").Append(SourceTenantId).Append("\n");
            sb.Append("  SourceChannelId: ").Append(SourceChannelId).Append("\n");
            sb.Append("  SourceLocationId: ").Append(SourceLocationId).Append("\n");
            sb.Append("  SourceOrderId: ").Append(SourceOrderId).Append("\n");
            sb.Append("  SourceOrderNumber: ").Append(SourceOrderNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SourceTenantId (string) maxLength
            if (this.SourceTenantId != null && this.SourceTenantId.Length > 50)
            {
                yield return new ValidationResult("Invalid value for SourceTenantId, length must be less than 50.", new [] { "SourceTenantId" });
            }

            // SourceTenantId (string) minLength
            if (this.SourceTenantId != null && this.SourceTenantId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for SourceTenantId, length must be greater than 1.", new [] { "SourceTenantId" });
            }

            // SourceLocationId (string) maxLength
            if (this.SourceLocationId != null && this.SourceLocationId.Length > 50)
            {
                yield return new ValidationResult("Invalid value for SourceLocationId, length must be less than 50.", new [] { "SourceLocationId" });
            }

            // SourceLocationId (string) minLength
            if (this.SourceLocationId != null && this.SourceLocationId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for SourceLocationId, length must be greater than 1.", new [] { "SourceLocationId" });
            }

            // SourceOrderId (string) maxLength
            if (this.SourceOrderId != null && this.SourceOrderId.Length > 50)
            {
                yield return new ValidationResult("Invalid value for SourceOrderId, length must be less than 50.", new [] { "SourceOrderId" });
            }

            // SourceOrderId (string) minLength
            if (this.SourceOrderId != null && this.SourceOrderId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for SourceOrderId, length must be greater than 1.", new [] { "SourceOrderId" });
            }

            // SourceOrderNumber (string) maxLength
            if (this.SourceOrderNumber != null && this.SourceOrderNumber.Length > 50)
            {
                yield return new ValidationResult("Invalid value for SourceOrderNumber, length must be less than 50.", new [] { "SourceOrderNumber" });
            }

            // SourceOrderNumber (string) minLength
            if (this.SourceOrderNumber != null && this.SourceOrderNumber.Length < 1)
            {
                yield return new ValidationResult("Invalid value for SourceOrderNumber, length must be greater than 1.", new [] { "SourceOrderNumber" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RefundTransactionContext" />
    /// </summary>
    public class RefundTransactionContextJsonConverter : JsonConverter<RefundTransactionContext>
    {
        /// <summary>
        /// Deserializes json to <see cref="RefundTransactionContext" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RefundTransactionContext Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> sourceTenantId = default;
            Option<string?> sourceChannelId = default;
            Option<string?> sourceLocationId = default;
            Option<string?> sourceOrderId = default;
            Option<string?> sourceOrderNumber = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sourceTenantId":
                            sourceTenantId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceChannelId":
                            sourceChannelId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceLocationId":
                            sourceLocationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceOrderId":
                            sourceOrderId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceOrderNumber":
                            sourceOrderNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (sourceTenantId.IsSet && sourceTenantId.Value == null)
                throw new ArgumentNullException(nameof(sourceTenantId), "Property is not nullable for class RefundTransactionContext.");

            if (sourceChannelId.IsSet && sourceChannelId.Value == null)
                throw new ArgumentNullException(nameof(sourceChannelId), "Property is not nullable for class RefundTransactionContext.");

            if (sourceLocationId.IsSet && sourceLocationId.Value == null)
                throw new ArgumentNullException(nameof(sourceLocationId), "Property is not nullable for class RefundTransactionContext.");

            if (sourceOrderId.IsSet && sourceOrderId.Value == null)
                throw new ArgumentNullException(nameof(sourceOrderId), "Property is not nullable for class RefundTransactionContext.");

            if (sourceOrderNumber.IsSet && sourceOrderNumber.Value == null)
                throw new ArgumentNullException(nameof(sourceOrderNumber), "Property is not nullable for class RefundTransactionContext.");

            return new RefundTransactionContext(sourceTenantId, sourceChannelId, sourceLocationId, sourceOrderId, sourceOrderNumber);
        }

        /// <summary>
        /// Serializes a <see cref="RefundTransactionContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundTransactionContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RefundTransactionContext refundTransactionContext, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, refundTransactionContext, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RefundTransactionContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="refundTransactionContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RefundTransactionContext refundTransactionContext, JsonSerializerOptions jsonSerializerOptions)
        {
            if (refundTransactionContext.SourceTenantIdOption.IsSet && refundTransactionContext.SourceTenantId == null)
                throw new ArgumentNullException(nameof(refundTransactionContext.SourceTenantId), "Property is required for class RefundTransactionContext.");

            if (refundTransactionContext.SourceChannelIdOption.IsSet && refundTransactionContext.SourceChannelId == null)
                throw new ArgumentNullException(nameof(refundTransactionContext.SourceChannelId), "Property is required for class RefundTransactionContext.");

            if (refundTransactionContext.SourceLocationIdOption.IsSet && refundTransactionContext.SourceLocationId == null)
                throw new ArgumentNullException(nameof(refundTransactionContext.SourceLocationId), "Property is required for class RefundTransactionContext.");

            if (refundTransactionContext.SourceOrderIdOption.IsSet && refundTransactionContext.SourceOrderId == null)
                throw new ArgumentNullException(nameof(refundTransactionContext.SourceOrderId), "Property is required for class RefundTransactionContext.");

            if (refundTransactionContext.SourceOrderNumberOption.IsSet && refundTransactionContext.SourceOrderNumber == null)
                throw new ArgumentNullException(nameof(refundTransactionContext.SourceOrderNumber), "Property is required for class RefundTransactionContext.");

            if (refundTransactionContext.SourceTenantIdOption.IsSet)
                writer.WriteString("sourceTenantId", refundTransactionContext.SourceTenantId);

            if (refundTransactionContext.SourceChannelIdOption.IsSet)
                writer.WriteString("sourceChannelId", refundTransactionContext.SourceChannelId);

            if (refundTransactionContext.SourceLocationIdOption.IsSet)
                writer.WriteString("sourceLocationId", refundTransactionContext.SourceLocationId);

            if (refundTransactionContext.SourceOrderIdOption.IsSet)
                writer.WriteString("sourceOrderId", refundTransactionContext.SourceOrderId);

            if (refundTransactionContext.SourceOrderNumberOption.IsSet)
                writer.WriteString("sourceOrderNumber", refundTransactionContext.SourceOrderNumber);
        }
    }
}
