// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Schedule
    /// </summary>
    public partial class Schedule : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Schedule" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="identifier">doesn&#39;t have to be unique. example: triggerName+entityId</param>
        /// <param name="configurationCorrelationId">configurationCorrelationId</param>
        /// <param name="activationId">activationId</param>
        /// <param name="scheduledAction">scheduledAction</param>
        /// <param name="eventPayload">Raw domain event, not enriched</param>
        /// <param name="scheduleStatus">scheduleStatus</param>
        /// <param name="scheduleDate">scheduleDate</param>
        /// <param name="createdDate">createdDate</param>
        /// <param name="updatedDate">updatedDate</param>
        /// <param name="overrideable">overrideable</param>
        /// <param name="triggerInfo">triggerInfo</param>
        /// <param name="automation">automation</param>
        [JsonConstructor]
        public Schedule(Option<string?> id = default, Option<string?> identifier = default, Option<string?> configurationCorrelationId = default, Option<string?> activationId = default, Option<Object?> scheduledAction = default, Option<string?> eventPayload = default, Option<string?> scheduleStatus = default, Option<DateTime?> scheduleDate = default, Option<DateTime?> createdDate = default, Option<DateTime?> updatedDate = default, Option<bool?> overrideable = default, Option<Object?> triggerInfo = default, Option<Object?> automation = default)
        {
            IdOption = id;
            IdentifierOption = identifier;
            ConfigurationCorrelationIdOption = configurationCorrelationId;
            ActivationIdOption = activationId;
            ScheduledActionOption = scheduledAction;
            EventPayloadOption = eventPayload;
            ScheduleStatusOption = scheduleStatus;
            ScheduleDateOption = scheduleDate;
            CreatedDateOption = createdDate;
            UpdatedDateOption = updatedDate;
            OverrideableOption = overrideable;
            TriggerInfoOption = triggerInfo;
            AutomationOption = automation;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } }

        /// <summary>
        /// Used to track the state of Identifier
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdentifierOption { get; private set; }

        /// <summary>
        /// doesn&#39;t have to be unique. example: triggerName+entityId
        /// </summary>
        /// <value>doesn&#39;t have to be unique. example: triggerName+entityId</value>
        [JsonPropertyName("identifier")]
        public string? Identifier { get { return this.IdentifierOption; } set { this.IdentifierOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConfigurationCorrelationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConfigurationCorrelationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConfigurationCorrelationId
        /// </summary>
        [JsonPropertyName("configurationCorrelationId")]
        public string? ConfigurationCorrelationId { get { return this.ConfigurationCorrelationIdOption; } set { this.ConfigurationCorrelationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ActivationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActivationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ActivationId
        /// </summary>
        [JsonPropertyName("activationId")]
        public string? ActivationId { get { return this.ActivationIdOption; } set { this.ActivationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ScheduledAction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ScheduledActionOption { get; private set; }

        /// <summary>
        /// Gets or Sets ScheduledAction
        /// </summary>
        [JsonPropertyName("scheduledAction")]
        public Object? ScheduledAction { get { return this.ScheduledActionOption; } set { this.ScheduledActionOption = new(value); } }

        /// <summary>
        /// Used to track the state of EventPayload
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EventPayloadOption { get; private set; }

        /// <summary>
        /// Raw domain event, not enriched
        /// </summary>
        /// <value>Raw domain event, not enriched</value>
        [JsonPropertyName("eventPayload")]
        public string? EventPayload { get { return this.EventPayloadOption; } set { this.EventPayloadOption = new(value); } }

        /// <summary>
        /// Used to track the state of ScheduleStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ScheduleStatusOption { get; }

        /// <summary>
        /// Gets or Sets ScheduleStatus
        /// </summary>
        [JsonPropertyName("scheduleStatus")]
        public string? ScheduleStatus { get { return this.ScheduleStatusOption; } }

        /// <summary>
        /// Used to track the state of ScheduleDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ScheduleDateOption { get; }

        /// <summary>
        /// Gets or Sets ScheduleDate
        /// </summary>
        [JsonPropertyName("scheduleDate")]
        public DateTime? ScheduleDate { get { return this.ScheduleDateOption; } }

        /// <summary>
        /// Used to track the state of CreatedDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedDateOption { get; }

        /// <summary>
        /// Gets or Sets CreatedDate
        /// </summary>
        [JsonPropertyName("createdDate")]
        public DateTime? CreatedDate { get { return this.CreatedDateOption; } }

        /// <summary>
        /// Used to track the state of UpdatedDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedDateOption { get; }

        /// <summary>
        /// Gets or Sets UpdatedDate
        /// </summary>
        [JsonPropertyName("updatedDate")]
        public DateTime? UpdatedDate { get { return this.UpdatedDateOption; } }

        /// <summary>
        /// Used to track the state of Overrideable
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> OverrideableOption { get; private set; }

        /// <summary>
        /// Gets or Sets Overrideable
        /// </summary>
        [JsonPropertyName("overrideable")]
        public bool? Overrideable { get { return this.OverrideableOption; } set { this.OverrideableOption = new(value); } }

        /// <summary>
        /// Used to track the state of TriggerInfo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> TriggerInfoOption { get; private set; }

        /// <summary>
        /// Gets or Sets TriggerInfo
        /// </summary>
        [JsonPropertyName("triggerInfo")]
        public Object? TriggerInfo { get { return this.TriggerInfoOption; } set { this.TriggerInfoOption = new(value); } }

        /// <summary>
        /// Used to track the state of Automation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> AutomationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Automation
        /// </summary>
        [JsonPropertyName("automation")]
        public Object? Automation { get { return this.AutomationOption; } set { this.AutomationOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Schedule {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  ConfigurationCorrelationId: ").Append(ConfigurationCorrelationId).Append("\n");
            sb.Append("  ActivationId: ").Append(ActivationId).Append("\n");
            sb.Append("  ScheduledAction: ").Append(ScheduledAction).Append("\n");
            sb.Append("  EventPayload: ").Append(EventPayload).Append("\n");
            sb.Append("  ScheduleStatus: ").Append(ScheduleStatus).Append("\n");
            sb.Append("  ScheduleDate: ").Append(ScheduleDate).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  UpdatedDate: ").Append(UpdatedDate).Append("\n");
            sb.Append("  Overrideable: ").Append(Overrideable).Append("\n");
            sb.Append("  TriggerInfo: ").Append(TriggerInfo).Append("\n");
            sb.Append("  Automation: ").Append(Automation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Identifier (string) maxLength
            if (this.Identifier != null && this.Identifier.Length > 300)
            {
                yield return new ValidationResult("Invalid value for Identifier, length must be less than 300.", new [] { "Identifier" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Schedule" />
    /// </summary>
    public class ScheduleJsonConverter : JsonConverter<Schedule>
    {
        /// <summary>
        /// The format to use to serialize ScheduleDate
        /// </summary>
        public static string ScheduleDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CreatedDate
        /// </summary>
        public static string CreatedDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedDate
        /// </summary>
        public static string UpdatedDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Schedule" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Schedule Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> identifier = default;
            Option<string?> configurationCorrelationId = default;
            Option<string?> activationId = default;
            Option<Object?> scheduledAction = default;
            Option<string?> eventPayload = default;
            Option<string?> scheduleStatus = default;
            Option<DateTime?> scheduleDate = default;
            Option<DateTime?> createdDate = default;
            Option<DateTime?> updatedDate = default;
            Option<bool?> overrideable = default;
            Option<Object?> triggerInfo = default;
            Option<Object?> automation = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "identifier":
                            identifier = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "configurationCorrelationId":
                            configurationCorrelationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "activationId":
                            activationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "scheduledAction":
                            scheduledAction = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "eventPayload":
                            eventPayload = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "scheduleStatus":
                            scheduleStatus = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "scheduleDate":
                            scheduleDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "createdDate":
                            createdDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedDate":
                            updatedDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "overrideable":
                            overrideable = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "triggerInfo":
                            triggerInfo = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "automation":
                            automation = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Schedule.");

            if (identifier.IsSet && identifier.Value == null)
                throw new ArgumentNullException(nameof(identifier), "Property is not nullable for class Schedule.");

            if (configurationCorrelationId.IsSet && configurationCorrelationId.Value == null)
                throw new ArgumentNullException(nameof(configurationCorrelationId), "Property is not nullable for class Schedule.");

            if (activationId.IsSet && activationId.Value == null)
                throw new ArgumentNullException(nameof(activationId), "Property is not nullable for class Schedule.");

            if (scheduledAction.IsSet && scheduledAction.Value == null)
                throw new ArgumentNullException(nameof(scheduledAction), "Property is not nullable for class Schedule.");

            if (eventPayload.IsSet && eventPayload.Value == null)
                throw new ArgumentNullException(nameof(eventPayload), "Property is not nullable for class Schedule.");

            if (scheduleStatus.IsSet && scheduleStatus.Value == null)
                throw new ArgumentNullException(nameof(scheduleStatus), "Property is not nullable for class Schedule.");

            if (scheduleDate.IsSet && scheduleDate.Value == null)
                throw new ArgumentNullException(nameof(scheduleDate), "Property is not nullable for class Schedule.");

            if (createdDate.IsSet && createdDate.Value == null)
                throw new ArgumentNullException(nameof(createdDate), "Property is not nullable for class Schedule.");

            if (updatedDate.IsSet && updatedDate.Value == null)
                throw new ArgumentNullException(nameof(updatedDate), "Property is not nullable for class Schedule.");

            if (overrideable.IsSet && overrideable.Value == null)
                throw new ArgumentNullException(nameof(overrideable), "Property is not nullable for class Schedule.");

            if (triggerInfo.IsSet && triggerInfo.Value == null)
                throw new ArgumentNullException(nameof(triggerInfo), "Property is not nullable for class Schedule.");

            if (automation.IsSet && automation.Value == null)
                throw new ArgumentNullException(nameof(automation), "Property is not nullable for class Schedule.");

            return new Schedule(id, identifier, configurationCorrelationId, activationId, scheduledAction, eventPayload, scheduleStatus, scheduleDate, createdDate, updatedDate, overrideable, triggerInfo, automation);
        }

        /// <summary>
        /// Serializes a <see cref="Schedule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="schedule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Schedule schedule, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, schedule, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Schedule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="schedule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Schedule schedule, JsonSerializerOptions jsonSerializerOptions)
        {
            if (schedule.IdOption.IsSet && schedule.Id == null)
                throw new ArgumentNullException(nameof(schedule.Id), "Property is required for class Schedule.");

            if (schedule.IdentifierOption.IsSet && schedule.Identifier == null)
                throw new ArgumentNullException(nameof(schedule.Identifier), "Property is required for class Schedule.");

            if (schedule.ConfigurationCorrelationIdOption.IsSet && schedule.ConfigurationCorrelationId == null)
                throw new ArgumentNullException(nameof(schedule.ConfigurationCorrelationId), "Property is required for class Schedule.");

            if (schedule.ActivationIdOption.IsSet && schedule.ActivationId == null)
                throw new ArgumentNullException(nameof(schedule.ActivationId), "Property is required for class Schedule.");

            if (schedule.ScheduledActionOption.IsSet && schedule.ScheduledAction == null)
                throw new ArgumentNullException(nameof(schedule.ScheduledAction), "Property is required for class Schedule.");

            if (schedule.EventPayloadOption.IsSet && schedule.EventPayload == null)
                throw new ArgumentNullException(nameof(schedule.EventPayload), "Property is required for class Schedule.");

            if (schedule.ScheduleStatusOption.IsSet && schedule.ScheduleStatus == null)
                throw new ArgumentNullException(nameof(schedule.ScheduleStatus), "Property is required for class Schedule.");

            if (schedule.TriggerInfoOption.IsSet && schedule.TriggerInfo == null)
                throw new ArgumentNullException(nameof(schedule.TriggerInfo), "Property is required for class Schedule.");

            if (schedule.AutomationOption.IsSet && schedule.Automation == null)
                throw new ArgumentNullException(nameof(schedule.Automation), "Property is required for class Schedule.");

            if (schedule.IdOption.IsSet)
                writer.WriteString("id", schedule.Id);

            if (schedule.IdentifierOption.IsSet)
                writer.WriteString("identifier", schedule.Identifier);

            if (schedule.ConfigurationCorrelationIdOption.IsSet)
                writer.WriteString("configurationCorrelationId", schedule.ConfigurationCorrelationId);

            if (schedule.ActivationIdOption.IsSet)
                writer.WriteString("activationId", schedule.ActivationId);

            if (schedule.ScheduledActionOption.IsSet)
            {
                writer.WritePropertyName("scheduledAction");
                JsonSerializer.Serialize(writer, schedule.ScheduledAction, jsonSerializerOptions);
            }
            if (schedule.EventPayloadOption.IsSet)
                writer.WriteString("eventPayload", schedule.EventPayload);

            if (schedule.ScheduleStatusOption.IsSet)
                writer.WriteString("scheduleStatus", schedule.ScheduleStatus);

            if (schedule.ScheduleDateOption.IsSet)
                writer.WriteString("scheduleDate", schedule.ScheduleDateOption.Value!.Value.ToString(ScheduleDateFormat));

            if (schedule.CreatedDateOption.IsSet)
                writer.WriteString("createdDate", schedule.CreatedDateOption.Value!.Value.ToString(CreatedDateFormat));

            if (schedule.UpdatedDateOption.IsSet)
                writer.WriteString("updatedDate", schedule.UpdatedDateOption.Value!.Value.ToString(UpdatedDateFormat));

            if (schedule.OverrideableOption.IsSet)
                writer.WriteBoolean("overrideable", schedule.OverrideableOption.Value!.Value);

            if (schedule.TriggerInfoOption.IsSet)
            {
                writer.WritePropertyName("triggerInfo");
                JsonSerializer.Serialize(writer, schedule.TriggerInfo, jsonSerializerOptions);
            }
            if (schedule.AutomationOption.IsSet)
            {
                writer.WritePropertyName("automation");
                JsonSerializer.Serialize(writer, schedule.Automation, jsonSerializerOptions);
            }
        }
    }
}
