// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SearchGiftCardsResponse1
    /// </summary>
    public partial class SearchGiftCardsResponse1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchGiftCardsResponse1" /> class.
        /// </summary>
        /// <param name="giftCards">Gift Cards which satisfy the provided query.</param>
        /// <param name="pagingMetadata">pagingMetadata</param>
        /// <param name="aggregationData">aggregationData</param>
        [JsonConstructor]
        public SearchGiftCardsResponse1(Option<List<GiftCard5>?> giftCards = default, Option<CursorPagingMetadata2?> pagingMetadata = default, Option<AggregationData1?> aggregationData = default)
        {
            GiftCardsOption = giftCards;
            PagingMetadataOption = pagingMetadata;
            AggregationDataOption = aggregationData;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of GiftCards
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<GiftCard5>?> GiftCardsOption { get; private set; }

        /// <summary>
        /// Gift Cards which satisfy the provided query.
        /// </summary>
        /// <value>Gift Cards which satisfy the provided query.</value>
        [JsonPropertyName("giftCards")]
        public List<GiftCard5>? GiftCards { get { return this.GiftCardsOption; } set { this.GiftCardsOption = new(value); } }

        /// <summary>
        /// Used to track the state of PagingMetadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CursorPagingMetadata2?> PagingMetadataOption { get; private set; }

        /// <summary>
        /// Gets or Sets PagingMetadata
        /// </summary>
        [JsonPropertyName("pagingMetadata")]
        public CursorPagingMetadata2? PagingMetadata { get { return this.PagingMetadataOption; } set { this.PagingMetadataOption = new(value); } }

        /// <summary>
        /// Used to track the state of AggregationData
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AggregationData1?> AggregationDataOption { get; private set; }

        /// <summary>
        /// Gets or Sets AggregationData
        /// </summary>
        [JsonPropertyName("aggregationData")]
        public AggregationData1? AggregationData { get { return this.AggregationDataOption; } set { this.AggregationDataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchGiftCardsResponse1 {\n");
            sb.Append("  GiftCards: ").Append(GiftCards).Append("\n");
            sb.Append("  PagingMetadata: ").Append(PagingMetadata).Append("\n");
            sb.Append("  AggregationData: ").Append(AggregationData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchGiftCardsResponse1" />
    /// </summary>
    public class SearchGiftCardsResponse1JsonConverter : JsonConverter<SearchGiftCardsResponse1>
    {
        /// <summary>
        /// Deserializes json to <see cref="SearchGiftCardsResponse1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SearchGiftCardsResponse1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<GiftCard5>?> giftCards = default;
            Option<CursorPagingMetadata2?> pagingMetadata = default;
            Option<AggregationData1?> aggregationData = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "giftCards":
                            giftCards = new Option<List<GiftCard5>?>(JsonSerializer.Deserialize<List<GiftCard5>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "pagingMetadata":
                            pagingMetadata = new Option<CursorPagingMetadata2?>(JsonSerializer.Deserialize<CursorPagingMetadata2>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "aggregationData":
                            aggregationData = new Option<AggregationData1?>(JsonSerializer.Deserialize<AggregationData1>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (giftCards.IsSet && giftCards.Value == null)
                throw new ArgumentNullException(nameof(giftCards), "Property is not nullable for class SearchGiftCardsResponse1.");

            if (pagingMetadata.IsSet && pagingMetadata.Value == null)
                throw new ArgumentNullException(nameof(pagingMetadata), "Property is not nullable for class SearchGiftCardsResponse1.");

            if (aggregationData.IsSet && aggregationData.Value == null)
                throw new ArgumentNullException(nameof(aggregationData), "Property is not nullable for class SearchGiftCardsResponse1.");

            return new SearchGiftCardsResponse1(giftCards, pagingMetadata, aggregationData);
        }

        /// <summary>
        /// Serializes a <see cref="SearchGiftCardsResponse1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchGiftCardsResponse1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SearchGiftCardsResponse1 searchGiftCardsResponse1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, searchGiftCardsResponse1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SearchGiftCardsResponse1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchGiftCardsResponse1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SearchGiftCardsResponse1 searchGiftCardsResponse1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (searchGiftCardsResponse1.GiftCardsOption.IsSet && searchGiftCardsResponse1.GiftCards == null)
                throw new ArgumentNullException(nameof(searchGiftCardsResponse1.GiftCards), "Property is required for class SearchGiftCardsResponse1.");

            if (searchGiftCardsResponse1.PagingMetadataOption.IsSet && searchGiftCardsResponse1.PagingMetadata == null)
                throw new ArgumentNullException(nameof(searchGiftCardsResponse1.PagingMetadata), "Property is required for class SearchGiftCardsResponse1.");

            if (searchGiftCardsResponse1.AggregationDataOption.IsSet && searchGiftCardsResponse1.AggregationData == null)
                throw new ArgumentNullException(nameof(searchGiftCardsResponse1.AggregationData), "Property is required for class SearchGiftCardsResponse1.");

            if (searchGiftCardsResponse1.GiftCardsOption.IsSet)
            {
                writer.WritePropertyName("giftCards");
                JsonSerializer.Serialize(writer, searchGiftCardsResponse1.GiftCards, jsonSerializerOptions);
            }
            if (searchGiftCardsResponse1.PagingMetadataOption.IsSet)
            {
                writer.WritePropertyName("pagingMetadata");
                JsonSerializer.Serialize(writer, searchGiftCardsResponse1.PagingMetadata, jsonSerializerOptions);
            }
            if (searchGiftCardsResponse1.AggregationDataOption.IsSet)
            {
                writer.WritePropertyName("aggregationData");
                JsonSerializer.Serialize(writer, searchGiftCardsResponse1.AggregationData, jsonSerializerOptions);
            }
        }
    }
}
