// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines SortType
    /// </summary>
    public enum SortType
    {
        /// <summary>
        /// Enum Order0valueCOUNTdescriptionNumberOfMatchesInTheResultsmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:0,\&quot;value\&quot;:\&quot;COUNT\&quot;,\&quot;description\&quot;:\&quot;Number of matches in the results.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
        /// </summary>
        Order0valueCOUNTdescriptionNumberOfMatchesInTheResultsmaturityGAexposurePUBLIC = 1,

        /// <summary>
        /// Enum Order1valueVALUEdescriptionAlphabeticallyByTheFieldValuematurityGAexposurePUBLIC for value: {\&quot;order\&quot;:1,\&quot;value\&quot;:\&quot;VALUE\&quot;,\&quot;description\&quot;:\&quot;Alphabetically by the field value.\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
        /// </summary>
        Order1valueVALUEdescriptionAlphabeticallyByTheFieldValuematurityGAexposurePUBLIC = 2
    }

    /// <summary>
    /// Converts <see cref="SortType"/> to and from the JSON value
    /// </summary>
    public static class SortTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SortType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SortType FromString(string value)
        {
            if (value.Equals("{\"order\":0,\"value\":\"COUNT\",\"description\":\"Number of matches in the results.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return SortType.Order0valueCOUNTdescriptionNumberOfMatchesInTheResultsmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":1,\"value\":\"VALUE\",\"description\":\"Alphabetically by the field value.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return SortType.Order1valueVALUEdescriptionAlphabeticallyByTheFieldValuematurityGAexposurePUBLIC;

            throw new NotImplementedException($"Could not convert value to type SortType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SortType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SortType? FromStringOrDefault(string value)
        {
            if (value.Equals("{\"order\":0,\"value\":\"COUNT\",\"description\":\"Number of matches in the results.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return SortType.Order0valueCOUNTdescriptionNumberOfMatchesInTheResultsmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":1,\"value\":\"VALUE\",\"description\":\"Alphabetically by the field value.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return SortType.Order1valueVALUEdescriptionAlphabeticallyByTheFieldValuematurityGAexposurePUBLIC;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SortType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SortType value)
        {
            if (value == SortType.Order0valueCOUNTdescriptionNumberOfMatchesInTheResultsmaturityGAexposurePUBLIC)
                return "{\"order\":0,\"value\":\"COUNT\",\"description\":\"Number of matches in the results.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == SortType.Order1valueVALUEdescriptionAlphabeticallyByTheFieldValuematurityGAexposurePUBLIC)
                return "{\"order\":1,\"value\":\"VALUE\",\"description\":\"Alphabetically by the field value.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SortType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SortTypeJsonConverter : JsonConverter<SortType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SortType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SortType? result = rawValue == null
                ? null
                : SortTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SortType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sortType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SortType sortType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SortTypeValueConverter.ToJsonValue(sortType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SortType"/>
    /// </summary>
    public class SortTypeNullableJsonConverter : JsonConverter<SortType?>
    {
        /// <summary>
        /// Returns a SortType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SortType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SortType? result = rawValue == null
                ? null
                : SortTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SortType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sortType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SortType? sortType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(sortType.HasValue ? SortTypeValueConverter.ToJsonValue(sortType.Value).ToString() : "null");
        }
    }
}
