// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Sorting2
    /// </summary>
    public partial class Sorting2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Sorting2" /> class.
        /// </summary>
        /// <param name="fieldName">Name of the field to sort by.</param>
        /// <param name="order">Sort order.</param>
        [JsonConstructor]
        public Sorting2(Option<string?> fieldName = default, Option<OrderEnum?> order = default)
        {
            FieldNameOption = fieldName;
            OrderOption = order;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Sort order.
        /// </summary>
        /// <value>Sort order.</value>
        public enum OrderEnum
        {
            /// <summary>
            /// Enum ASC for value: ASC
            /// </summary>
            ASC = 1,

            /// <summary>
            /// Enum DESC for value: DESC
            /// </summary>
            DESC = 2
        }

        /// <summary>
        /// Returns a <see cref="OrderEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static OrderEnum OrderEnumFromString(string value)
        {
            if (value.Equals("ASC"))
                return OrderEnum.ASC;

            if (value.Equals("DESC"))
                return OrderEnum.DESC;

            throw new NotImplementedException($"Could not convert value to type OrderEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="OrderEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OrderEnum? OrderEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ASC"))
                return OrderEnum.ASC;

            if (value.Equals("DESC"))
                return OrderEnum.DESC;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OrderEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string OrderEnumToJsonValue(OrderEnum? value)
        {
            if (value == OrderEnum.ASC)
                return "ASC";

            if (value == OrderEnum.DESC)
                return "DESC";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Order
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<OrderEnum?> OrderOption { get; private set; }

        /// <summary>
        /// Sort order.
        /// </summary>
        /// <value>Sort order.</value>
        [JsonPropertyName("order")]
        public OrderEnum? Order { get { return this.OrderOption; } set { this.OrderOption = new(value); } }

        /// <summary>
        /// Used to track the state of FieldName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FieldNameOption { get; private set; }

        /// <summary>
        /// Name of the field to sort by.
        /// </summary>
        /// <value>Name of the field to sort by.</value>
        [JsonPropertyName("fieldName")]
        public string? FieldName { get { return this.FieldNameOption; } set { this.FieldNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Sorting2 {\n");
            sb.Append("  FieldName: ").Append(FieldName).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Sorting2" />
    /// </summary>
    public class Sorting2JsonConverter : JsonConverter<Sorting2>
    {
        /// <summary>
        /// Deserializes json to <see cref="Sorting2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Sorting2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> fieldName = default;
            Option<Sorting2.OrderEnum?> order = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "fieldName":
                            fieldName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "order":
                            string? orderRawValue = utf8JsonReader.GetString();
                            if (orderRawValue != null)
                                order = new Option<Sorting2.OrderEnum?>(Sorting2.OrderEnumFromStringOrDefault(orderRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (fieldName.IsSet && fieldName.Value == null)
                throw new ArgumentNullException(nameof(fieldName), "Property is not nullable for class Sorting2.");

            if (order.IsSet && order.Value == null)
                throw new ArgumentNullException(nameof(order), "Property is not nullable for class Sorting2.");

            return new Sorting2(fieldName, order);
        }

        /// <summary>
        /// Serializes a <see cref="Sorting2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sorting2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Sorting2 sorting2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sorting2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Sorting2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sorting2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Sorting2 sorting2, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sorting2.FieldNameOption.IsSet && sorting2.FieldName == null)
                throw new ArgumentNullException(nameof(sorting2.FieldName), "Property is required for class Sorting2.");

            if (sorting2.FieldNameOption.IsSet)
                writer.WriteString("fieldName", sorting2.FieldName);

            var orderRawValue = Sorting2.OrderEnumToJsonValue(sorting2.OrderOption.Value!.Value);
            writer.WriteString("order", orderRawValue);
        }
    }
}
