// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines StoreCreditIssuerType
    /// </summary>
    public enum StoreCreditIssuerType
    {
        /// <summary>
        /// Enum WORKFLOW for value: WORKFLOW
        /// </summary>
        WORKFLOW = 1,

        /// <summary>
        /// Enum BULK for value: BULK
        /// </summary>
        BULK = 2,

        /// <summary>
        /// Enum MANUAL for value: MANUAL
        /// </summary>
        MANUAL = 3,

        /// <summary>
        /// Enum OTHER for value: OTHER
        /// </summary>
        OTHER = 4,

        /// <summary>
        /// Enum REFUND for value: REFUND
        /// </summary>
        REFUND = 5,

        /// <summary>
        /// Enum REFERRALREFERREDCUSTOMER for value: REFERRAL_REFERRED_CUSTOMER
        /// </summary>
        REFERRALREFERREDCUSTOMER = 6,

        /// <summary>
        /// Enum REFERRALREFERRER for value: REFERRAL_REFERRER
        /// </summary>
        REFERRALREFERRER = 7
    }

    /// <summary>
    /// Converts <see cref="StoreCreditIssuerType"/> to and from the JSON value
    /// </summary>
    public static class StoreCreditIssuerTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="StoreCreditIssuerType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StoreCreditIssuerType FromString(string value)
        {
            if (value.Equals("WORKFLOW"))
                return StoreCreditIssuerType.WORKFLOW;

            if (value.Equals("BULK"))
                return StoreCreditIssuerType.BULK;

            if (value.Equals("MANUAL"))
                return StoreCreditIssuerType.MANUAL;

            if (value.Equals("OTHER"))
                return StoreCreditIssuerType.OTHER;

            if (value.Equals("REFUND"))
                return StoreCreditIssuerType.REFUND;

            if (value.Equals("REFERRAL_REFERRED_CUSTOMER"))
                return StoreCreditIssuerType.REFERRALREFERREDCUSTOMER;

            if (value.Equals("REFERRAL_REFERRER"))
                return StoreCreditIssuerType.REFERRALREFERRER;

            throw new NotImplementedException($"Could not convert value to type StoreCreditIssuerType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="StoreCreditIssuerType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StoreCreditIssuerType? FromStringOrDefault(string value)
        {
            if (value.Equals("WORKFLOW"))
                return StoreCreditIssuerType.WORKFLOW;

            if (value.Equals("BULK"))
                return StoreCreditIssuerType.BULK;

            if (value.Equals("MANUAL"))
                return StoreCreditIssuerType.MANUAL;

            if (value.Equals("OTHER"))
                return StoreCreditIssuerType.OTHER;

            if (value.Equals("REFUND"))
                return StoreCreditIssuerType.REFUND;

            if (value.Equals("REFERRAL_REFERRED_CUSTOMER"))
                return StoreCreditIssuerType.REFERRALREFERREDCUSTOMER;

            if (value.Equals("REFERRAL_REFERRER"))
                return StoreCreditIssuerType.REFERRALREFERRER;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StoreCreditIssuerType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(StoreCreditIssuerType value)
        {
            if (value == StoreCreditIssuerType.WORKFLOW)
                return "WORKFLOW";

            if (value == StoreCreditIssuerType.BULK)
                return "BULK";

            if (value == StoreCreditIssuerType.MANUAL)
                return "MANUAL";

            if (value == StoreCreditIssuerType.OTHER)
                return "OTHER";

            if (value == StoreCreditIssuerType.REFUND)
                return "REFUND";

            if (value == StoreCreditIssuerType.REFERRALREFERREDCUSTOMER)
                return "REFERRAL_REFERRED_CUSTOMER";

            if (value == StoreCreditIssuerType.REFERRALREFERRER)
                return "REFERRAL_REFERRER";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StoreCreditIssuerType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class StoreCreditIssuerTypeJsonConverter : JsonConverter<StoreCreditIssuerType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override StoreCreditIssuerType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            StoreCreditIssuerType? result = rawValue == null
                ? null
                : StoreCreditIssuerTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the StoreCreditIssuerType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="storeCreditIssuerType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, StoreCreditIssuerType storeCreditIssuerType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(StoreCreditIssuerTypeValueConverter.ToJsonValue(storeCreditIssuerType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StoreCreditIssuerType"/>
    /// </summary>
    public class StoreCreditIssuerTypeNullableJsonConverter : JsonConverter<StoreCreditIssuerType?>
    {
        /// <summary>
        /// Returns a StoreCreditIssuerType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override StoreCreditIssuerType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            StoreCreditIssuerType? result = rawValue == null
                ? null
                : StoreCreditIssuerTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the StoreCreditIssuerType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="storeCreditIssuerType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, StoreCreditIssuerType? storeCreditIssuerType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(storeCreditIssuerType.HasValue ? StoreCreditIssuerTypeValueConverter.ToJsonValue(storeCreditIssuerType.Value).ToString() : "null");
        }
    }
}
