// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Detailed information about the context of a store credit, such as the issuer type and sales channel.
    /// </summary>
    public partial class StoreCreditContext2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StoreCreditContext2" /> class.
        /// </summary>
        /// <param name="issuer">The issuer type of the store credit (e.g., workflow, bulk, manual)</param>
        /// <param name="issuerId">Indicates a specific instance of the issuer (relevant for workflow/bulk)</param>
        /// <param name="note">An internal note associated with the store credit</param>
        /// <param name="sourceChannelId">The Channel ID of the sales channel that is associated with the store credit (e.g. Shopify channel id)</param>
        /// <param name="sourceTenantId">The Tenant ID of the sales channel that is associated with the store credit (e.g. Shopify shop id)</param>
        [JsonConstructor]
        public StoreCreditContext2(Option<IssuerEnum?> issuer = default, Option<string?> issuerId = default, Option<string?> note = default, Option<string?> sourceChannelId = default, Option<string?> sourceTenantId = default)
        {
            IssuerOption = issuer;
            IssuerIdOption = issuerId;
            NoteOption = note;
            SourceChannelIdOption = sourceChannelId;
            SourceTenantIdOption = sourceTenantId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The issuer type of the store credit (e.g., workflow, bulk, manual)
        /// </summary>
        /// <value>The issuer type of the store credit (e.g., workflow, bulk, manual)</value>
        public enum IssuerEnum
        {
            /// <summary>
            /// Enum Order1valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:1,\&quot;value\&quot;:\&quot;WORKFLOW\&quot;,\&quot;description\&quot;:\&quot;Issued from a workflow\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order1valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC = 1,

            /// <summary>
            /// Enum Order2valueBULKdescriptionIssuedFromABulkmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:2,\&quot;value\&quot;:\&quot;BULK\&quot;,\&quot;description\&quot;:\&quot;Issued from a bulk\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order2valueBULKdescriptionIssuedFromABulkmaturityGAexposurePUBLIC = 2,

            /// <summary>
            /// Enum Order3valueMANUALdescriptionIssuedFromTheRiseDashboardmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:3,\&quot;value\&quot;:\&quot;MANUAL\&quot;,\&quot;description\&quot;:\&quot;Issued from the Rise dashboard\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order3valueMANUALdescriptionIssuedFromTheRiseDashboardmaturityGAexposurePUBLIC = 3,

            /// <summary>
            /// Enum Order4valueOTHERdescriptionIssuedFromAnotherSourcematurityGAexposurePUBLIC for value: {\&quot;order\&quot;:4,\&quot;value\&quot;:\&quot;OTHER\&quot;,\&quot;description\&quot;:\&quot;Issued from another source\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order4valueOTHERdescriptionIssuedFromAnotherSourcematurityGAexposurePUBLIC = 4,

            /// <summary>
            /// Enum Order5valueREFUNDdescriptionIssuedFromARefundmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:5,\&quot;value\&quot;:\&quot;REFUND\&quot;,\&quot;description\&quot;:\&quot;Issued from a refund\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order5valueREFUNDdescriptionIssuedFromARefundmaturityGAexposurePUBLIC = 5,

            /// <summary>
            /// Enum Order6valueREFERRALREFERREDCUSTOMERdescriptionIssuedFromAReferralAReferredCustomerCreatedAWalletFromTheReferralLinkmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:6,\&quot;value\&quot;:\&quot;REFERRAL_REFERRED_CUSTOMER\&quot;,\&quot;description\&quot;:\&quot;Issued from a referral - a referred customer created a wallet from the referral link\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order6valueREFERRALREFERREDCUSTOMERdescriptionIssuedFromAReferralAReferredCustomerCreatedAWalletFromTheReferralLinkmaturityGAexposurePUBLIC = 6,

            /// <summary>
            /// Enum Order7valueREFERRALREFERRERdescriptionIssuedFromAReferralAReferrerMadeASuccessfulReferralTheReferredCustomerPlacedTheFirstOrdermaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:7,\&quot;value\&quot;:\&quot;REFERRAL_REFERRER\&quot;,\&quot;description\&quot;:\&quot;Issued from a referral - a referrer made a successful referral. The referred customer placed the first order\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order7valueREFERRALREFERRERdescriptionIssuedFromAReferralAReferrerMadeASuccessfulReferralTheReferredCustomerPlacedTheFirstOrdermaturityGAexposurePUBLIC = 7
        }

        /// <summary>
        /// Returns a <see cref="IssuerEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static IssuerEnum IssuerEnumFromString(string value)
        {
            if (value.Equals("{\"order\":1,\"value\":\"WORKFLOW\",\"description\":\"Issued from a workflow\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order1valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":2,\"value\":\"BULK\",\"description\":\"Issued from a bulk\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order2valueBULKdescriptionIssuedFromABulkmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":3,\"value\":\"MANUAL\",\"description\":\"Issued from the Rise dashboard\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order3valueMANUALdescriptionIssuedFromTheRiseDashboardmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":4,\"value\":\"OTHER\",\"description\":\"Issued from another source\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order4valueOTHERdescriptionIssuedFromAnotherSourcematurityGAexposurePUBLIC;

            if (value.Equals("{\"order\":5,\"value\":\"REFUND\",\"description\":\"Issued from a refund\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order5valueREFUNDdescriptionIssuedFromARefundmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":6,\"value\":\"REFERRAL_REFERRED_CUSTOMER\",\"description\":\"Issued from a referral - a referred customer created a wallet from the referral link\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order6valueREFERRALREFERREDCUSTOMERdescriptionIssuedFromAReferralAReferredCustomerCreatedAWalletFromTheReferralLinkmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":7,\"value\":\"REFERRAL_REFERRER\",\"description\":\"Issued from a referral - a referrer made a successful referral. The referred customer placed the first order\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order7valueREFERRALREFERRERdescriptionIssuedFromAReferralAReferrerMadeASuccessfulReferralTheReferredCustomerPlacedTheFirstOrdermaturityGAexposurePUBLIC;

            throw new NotImplementedException($"Could not convert value to type IssuerEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="IssuerEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static IssuerEnum? IssuerEnumFromStringOrDefault(string value)
        {
            if (value.Equals("{\"order\":1,\"value\":\"WORKFLOW\",\"description\":\"Issued from a workflow\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order1valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":2,\"value\":\"BULK\",\"description\":\"Issued from a bulk\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order2valueBULKdescriptionIssuedFromABulkmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":3,\"value\":\"MANUAL\",\"description\":\"Issued from the Rise dashboard\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order3valueMANUALdescriptionIssuedFromTheRiseDashboardmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":4,\"value\":\"OTHER\",\"description\":\"Issued from another source\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order4valueOTHERdescriptionIssuedFromAnotherSourcematurityGAexposurePUBLIC;

            if (value.Equals("{\"order\":5,\"value\":\"REFUND\",\"description\":\"Issued from a refund\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order5valueREFUNDdescriptionIssuedFromARefundmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":6,\"value\":\"REFERRAL_REFERRED_CUSTOMER\",\"description\":\"Issued from a referral - a referred customer created a wallet from the referral link\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order6valueREFERRALREFERREDCUSTOMERdescriptionIssuedFromAReferralAReferredCustomerCreatedAWalletFromTheReferralLinkmaturityGAexposurePUBLIC;

            if (value.Equals("{\"order\":7,\"value\":\"REFERRAL_REFERRER\",\"description\":\"Issued from a referral - a referrer made a successful referral. The referred customer placed the first order\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return IssuerEnum.Order7valueREFERRALREFERRERdescriptionIssuedFromAReferralAReferrerMadeASuccessfulReferralTheReferredCustomerPlacedTheFirstOrdermaturityGAexposurePUBLIC;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="IssuerEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string IssuerEnumToJsonValue(IssuerEnum? value)
        {
            if (value == IssuerEnum.Order1valueWORKFLOWdescriptionIssuedFromAWorkflowmaturityGAexposurePUBLIC)
                return "{\"order\":1,\"value\":\"WORKFLOW\",\"description\":\"Issued from a workflow\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == IssuerEnum.Order2valueBULKdescriptionIssuedFromABulkmaturityGAexposurePUBLIC)
                return "{\"order\":2,\"value\":\"BULK\",\"description\":\"Issued from a bulk\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == IssuerEnum.Order3valueMANUALdescriptionIssuedFromTheRiseDashboardmaturityGAexposurePUBLIC)
                return "{\"order\":3,\"value\":\"MANUAL\",\"description\":\"Issued from the Rise dashboard\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == IssuerEnum.Order4valueOTHERdescriptionIssuedFromAnotherSourcematurityGAexposurePUBLIC)
                return "{\"order\":4,\"value\":\"OTHER\",\"description\":\"Issued from another source\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == IssuerEnum.Order5valueREFUNDdescriptionIssuedFromARefundmaturityGAexposurePUBLIC)
                return "{\"order\":5,\"value\":\"REFUND\",\"description\":\"Issued from a refund\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == IssuerEnum.Order6valueREFERRALREFERREDCUSTOMERdescriptionIssuedFromAReferralAReferredCustomerCreatedAWalletFromTheReferralLinkmaturityGAexposurePUBLIC)
                return "{\"order\":6,\"value\":\"REFERRAL_REFERRED_CUSTOMER\",\"description\":\"Issued from a referral - a referred customer created a wallet from the referral link\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            if (value == IssuerEnum.Order7valueREFERRALREFERRERdescriptionIssuedFromAReferralAReferrerMadeASuccessfulReferralTheReferredCustomerPlacedTheFirstOrdermaturityGAexposurePUBLIC)
                return "{\"order\":7,\"value\":\"REFERRAL_REFERRER\",\"description\":\"Issued from a referral - a referrer made a successful referral. The referred customer placed the first order\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Issuer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<IssuerEnum?> IssuerOption { get; private set; }

        /// <summary>
        /// The issuer type of the store credit (e.g., workflow, bulk, manual)
        /// </summary>
        /// <value>The issuer type of the store credit (e.g., workflow, bulk, manual)</value>
        [JsonPropertyName("issuer")]
        public IssuerEnum? Issuer { get { return this.IssuerOption; } set { this.IssuerOption = new(value); } }

        /// <summary>
        /// Used to track the state of IssuerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IssuerIdOption { get; private set; }

        /// <summary>
        /// Indicates a specific instance of the issuer (relevant for workflow/bulk)
        /// </summary>
        /// <value>Indicates a specific instance of the issuer (relevant for workflow/bulk)</value>
        [JsonPropertyName("issuerId")]
        public string? IssuerId { get { return this.IssuerIdOption; } set { this.IssuerIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Note
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NoteOption { get; private set; }

        /// <summary>
        /// An internal note associated with the store credit
        /// </summary>
        /// <value>An internal note associated with the store credit</value>
        [JsonPropertyName("note")]
        public string? Note { get { return this.NoteOption; } set { this.NoteOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceChannelId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceChannelIdOption { get; private set; }

        /// <summary>
        /// The Channel ID of the sales channel that is associated with the store credit (e.g. Shopify channel id)
        /// </summary>
        /// <value>The Channel ID of the sales channel that is associated with the store credit (e.g. Shopify channel id)</value>
        [JsonPropertyName("sourceChannelId")]
        public string? SourceChannelId { get { return this.SourceChannelIdOption; } set { this.SourceChannelIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceTenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SourceTenantIdOption { get; private set; }

        /// <summary>
        /// The Tenant ID of the sales channel that is associated with the store credit (e.g. Shopify shop id)
        /// </summary>
        /// <value>The Tenant ID of the sales channel that is associated with the store credit (e.g. Shopify shop id)</value>
        [JsonPropertyName("sourceTenantId")]
        public string? SourceTenantId { get { return this.SourceTenantIdOption; } set { this.SourceTenantIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StoreCreditContext2 {\n");
            sb.Append("  Issuer: ").Append(Issuer).Append("\n");
            sb.Append("  IssuerId: ").Append(IssuerId).Append("\n");
            sb.Append("  Note: ").Append(Note).Append("\n");
            sb.Append("  SourceChannelId: ").Append(SourceChannelId).Append("\n");
            sb.Append("  SourceTenantId: ").Append(SourceTenantId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // IssuerId (string) maxLength
            if (this.IssuerId != null && this.IssuerId.Length > 50)
            {
                yield return new ValidationResult("Invalid value for IssuerId, length must be less than 50.", new [] { "IssuerId" });
            }

            // IssuerId (string) minLength
            if (this.IssuerId != null && this.IssuerId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for IssuerId, length must be greater than 1.", new [] { "IssuerId" });
            }

            // Note (string) maxLength
            if (this.Note != null && this.Note.Length > 550)
            {
                yield return new ValidationResult("Invalid value for Note, length must be less than 550.", new [] { "Note" });
            }

            // Note (string) minLength
            if (this.Note != null && this.Note.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Note, length must be greater than 1.", new [] { "Note" });
            }

            // SourceTenantId (string) maxLength
            if (this.SourceTenantId != null && this.SourceTenantId.Length > 50)
            {
                yield return new ValidationResult("Invalid value for SourceTenantId, length must be less than 50.", new [] { "SourceTenantId" });
            }

            // SourceTenantId (string) minLength
            if (this.SourceTenantId != null && this.SourceTenantId.Length < 1)
            {
                yield return new ValidationResult("Invalid value for SourceTenantId, length must be greater than 1.", new [] { "SourceTenantId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="StoreCreditContext2" />
    /// </summary>
    public class StoreCreditContext2JsonConverter : JsonConverter<StoreCreditContext2>
    {
        /// <summary>
        /// Deserializes json to <see cref="StoreCreditContext2" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override StoreCreditContext2 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<StoreCreditContext2.IssuerEnum?> issuer = default;
            Option<string?> issuerId = default;
            Option<string?> note = default;
            Option<string?> sourceChannelId = default;
            Option<string?> sourceTenantId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "issuer":
                            string? issuerRawValue = utf8JsonReader.GetString();
                            if (issuerRawValue != null)
                                issuer = new Option<StoreCreditContext2.IssuerEnum?>(StoreCreditContext2.IssuerEnumFromStringOrDefault(issuerRawValue));
                            break;
                        case "issuerId":
                            issuerId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "note":
                            note = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceChannelId":
                            sourceChannelId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sourceTenantId":
                            sourceTenantId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (issuer.IsSet && issuer.Value == null)
                throw new ArgumentNullException(nameof(issuer), "Property is not nullable for class StoreCreditContext2.");

            if (issuerId.IsSet && issuerId.Value == null)
                throw new ArgumentNullException(nameof(issuerId), "Property is not nullable for class StoreCreditContext2.");

            if (note.IsSet && note.Value == null)
                throw new ArgumentNullException(nameof(note), "Property is not nullable for class StoreCreditContext2.");

            if (sourceChannelId.IsSet && sourceChannelId.Value == null)
                throw new ArgumentNullException(nameof(sourceChannelId), "Property is not nullable for class StoreCreditContext2.");

            if (sourceTenantId.IsSet && sourceTenantId.Value == null)
                throw new ArgumentNullException(nameof(sourceTenantId), "Property is not nullable for class StoreCreditContext2.");

            return new StoreCreditContext2(issuer, issuerId, note, sourceChannelId, sourceTenantId);
        }

        /// <summary>
        /// Serializes a <see cref="StoreCreditContext2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="storeCreditContext2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, StoreCreditContext2 storeCreditContext2, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, storeCreditContext2, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="StoreCreditContext2" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="storeCreditContext2"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, StoreCreditContext2 storeCreditContext2, JsonSerializerOptions jsonSerializerOptions)
        {
            if (storeCreditContext2.IssuerIdOption.IsSet && storeCreditContext2.IssuerId == null)
                throw new ArgumentNullException(nameof(storeCreditContext2.IssuerId), "Property is required for class StoreCreditContext2.");

            if (storeCreditContext2.NoteOption.IsSet && storeCreditContext2.Note == null)
                throw new ArgumentNullException(nameof(storeCreditContext2.Note), "Property is required for class StoreCreditContext2.");

            if (storeCreditContext2.SourceChannelIdOption.IsSet && storeCreditContext2.SourceChannelId == null)
                throw new ArgumentNullException(nameof(storeCreditContext2.SourceChannelId), "Property is required for class StoreCreditContext2.");

            if (storeCreditContext2.SourceTenantIdOption.IsSet && storeCreditContext2.SourceTenantId == null)
                throw new ArgumentNullException(nameof(storeCreditContext2.SourceTenantId), "Property is required for class StoreCreditContext2.");

            var issuerRawValue = StoreCreditContext2.IssuerEnumToJsonValue(storeCreditContext2.IssuerOption.Value!.Value);
            writer.WriteString("issuer", issuerRawValue);
            if (storeCreditContext2.IssuerIdOption.IsSet)
                writer.WriteString("issuerId", storeCreditContext2.IssuerId);

            if (storeCreditContext2.NoteOption.IsSet)
                writer.WriteString("note", storeCreditContext2.Note);

            if (storeCreditContext2.SourceChannelIdOption.IsSet)
                writer.WriteString("sourceChannelId", storeCreditContext2.SourceChannelId);

            if (storeCreditContext2.SourceTenantIdOption.IsSet)
                writer.WriteString("sourceTenantId", storeCreditContext2.SourceTenantId);
        }
    }
}
