// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines Units
    /// </summary>
    public enum Units
    {
        /// <summary>
        /// Enum UNKNOWN for value: UNKNOWN
        /// </summary>
        UNKNOWN,

        /// <summary>
        /// Enum MINUTES for value: MINUTES
        /// </summary>
        MINUTES,

        /// <summary>
        /// Enum HOURS for value: HOURS
        /// </summary>
        HOURS,

        /// <summary>
        /// Enum DAYS for value: DAYS
        /// </summary>
        DAYS
    }

    /// <summary>
    /// Converts <see cref="Units"/> to and from the JSON value
    /// </summary>
    public static class UnitsValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="Units"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static Units FromString(string value)
        {
            if (value.Equals("UNKNOWN"))
                return Units.UNKNOWN;

            if (value.Equals("MINUTES"))
                return Units.MINUTES;

            if (value.Equals("HOURS"))
                return Units.HOURS;

            if (value.Equals("DAYS"))
                return Units.DAYS;

            throw new NotImplementedException($"Could not convert value to type Units: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="Units"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static Units? FromStringOrDefault(string value)
        {
            if (value.Equals("UNKNOWN"))
                return Units.UNKNOWN;

            if (value.Equals("MINUTES"))
                return Units.MINUTES;

            if (value.Equals("HOURS"))
                return Units.HOURS;

            if (value.Equals("DAYS"))
                return Units.DAYS;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="Units"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(Units value)
        {
            if (value == Units.UNKNOWN)
                return "UNKNOWN";

            if (value == Units.MINUTES)
                return "MINUTES";

            if (value == Units.HOURS)
                return "HOURS";

            if (value == Units.DAYS)
                return "DAYS";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Units"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class UnitsJsonConverter : JsonConverter<Units>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override Units Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            Units? result = rawValue == null
                ? null
                : UnitsValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the Units to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="units"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, Units units, JsonSerializerOptions options)
        {
            writer.WriteStringValue(UnitsValueConverter.ToJsonValue(units).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Units"/>
    /// </summary>
    public class UnitsNullableJsonConverter : JsonConverter<Units?>
    {
        /// <summary>
        /// Returns a Units from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override Units? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            Units? result = rawValue == null
                ? null
                : UnitsValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the Units to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="units"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, Units? units, JsonSerializerOptions options)
        {
            writer.WriteStringValue(units.HasValue ? UnitsValueConverter.ToJsonValue(units.Value).ToString() : "null");
        }
    }
}
