// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Value1
    /// </summary>
    public partial class Value1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Value1" /> class.
        /// </summary>
        /// <param name="nullValue1"></param>
        /// <param name="nullValue">nullValue</param>
        /// <param name="numberValue">numberValue</param>
        /// <param name="stringValue">stringValue</param>
        /// <param name="boolValue">boolValue</param>
        /// <param name="structValue">Circular reference to #/components/schemas/google.protobuf.Struct (simplified)</param>
        /// <param name="listValue">listValue</param>
        public Value1(NullValue nullValue1, Option<NullValueEnum?> nullValue = default, Option<decimal?> numberValue = default, Option<string?> stringValue = default, Option<bool?> boolValue = default, Option<Object?> structValue = default, Option<ListValue?> listValue = default)
        {
            NullValue1 = nullValue1;
            NullValueOption = nullValue;
            NumberValueOption = numberValue;
            StringValueOption = stringValue;
            BoolValueOption = boolValue;
            StructValueOption = structValue;
            ListValueOption = listValue;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Value1" /> class.
        /// </summary>
        /// <param name="numberValue1"></param>
        /// <param name="nullValue">nullValue</param>
        /// <param name="numberValue">numberValue</param>
        /// <param name="stringValue">stringValue</param>
        /// <param name="boolValue">boolValue</param>
        /// <param name="structValue">Circular reference to #/components/schemas/google.protobuf.Struct (simplified)</param>
        /// <param name="listValue">listValue</param>
        public Value1(NumberValue numberValue1, Option<NullValueEnum?> nullValue = default, Option<decimal?> numberValue = default, Option<string?> stringValue = default, Option<bool?> boolValue = default, Option<Object?> structValue = default, Option<ListValue?> listValue = default)
        {
            NumberValue1 = numberValue1;
            NullValueOption = nullValue;
            NumberValueOption = numberValue;
            StringValueOption = stringValue;
            BoolValueOption = boolValue;
            StructValueOption = structValue;
            ListValueOption = listValue;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Value1" /> class.
        /// </summary>
        /// <param name="stringValue1"></param>
        /// <param name="nullValue">nullValue</param>
        /// <param name="numberValue">numberValue</param>
        /// <param name="stringValue">stringValue</param>
        /// <param name="boolValue">boolValue</param>
        /// <param name="structValue">Circular reference to #/components/schemas/google.protobuf.Struct (simplified)</param>
        /// <param name="listValue">listValue</param>
        public Value1(StringValue stringValue1, Option<NullValueEnum?> nullValue = default, Option<decimal?> numberValue = default, Option<string?> stringValue = default, Option<bool?> boolValue = default, Option<Object?> structValue = default, Option<ListValue?> listValue = default)
        {
            StringValue1 = stringValue1;
            NullValueOption = nullValue;
            NumberValueOption = numberValue;
            StringValueOption = stringValue;
            BoolValueOption = boolValue;
            StructValueOption = structValue;
            ListValueOption = listValue;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Value1" /> class.
        /// </summary>
        /// <param name="boolValue1"></param>
        /// <param name="nullValue">nullValue</param>
        /// <param name="numberValue">numberValue</param>
        /// <param name="stringValue">stringValue</param>
        /// <param name="boolValue">boolValue</param>
        /// <param name="structValue">Circular reference to #/components/schemas/google.protobuf.Struct (simplified)</param>
        /// <param name="listValue">listValue</param>
        public Value1(BoolValue boolValue1, Option<NullValueEnum?> nullValue = default, Option<decimal?> numberValue = default, Option<string?> stringValue = default, Option<bool?> boolValue = default, Option<Object?> structValue = default, Option<ListValue?> listValue = default)
        {
            BoolValue1 = boolValue1;
            NullValueOption = nullValue;
            NumberValueOption = numberValue;
            StringValueOption = stringValue;
            BoolValueOption = boolValue;
            StructValueOption = structValue;
            ListValueOption = listValue;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Value1" /> class.
        /// </summary>
        /// <param name="structValue1"></param>
        /// <param name="nullValue">nullValue</param>
        /// <param name="numberValue">numberValue</param>
        /// <param name="stringValue">stringValue</param>
        /// <param name="boolValue">boolValue</param>
        /// <param name="structValue">Circular reference to #/components/schemas/google.protobuf.Struct (simplified)</param>
        /// <param name="listValue">listValue</param>
        public Value1(StructValue structValue1, Option<NullValueEnum?> nullValue = default, Option<decimal?> numberValue = default, Option<string?> stringValue = default, Option<bool?> boolValue = default, Option<Object?> structValue = default, Option<ListValue?> listValue = default)
        {
            StructValue1 = structValue1;
            NullValueOption = nullValue;
            NumberValueOption = numberValue;
            StringValueOption = stringValue;
            BoolValueOption = boolValue;
            StructValueOption = structValue;
            ListValueOption = listValue;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Value1" /> class.
        /// </summary>
        /// <param name="listValue1"></param>
        /// <param name="nullValue">nullValue</param>
        /// <param name="numberValue">numberValue</param>
        /// <param name="stringValue">stringValue</param>
        /// <param name="boolValue">boolValue</param>
        /// <param name="structValue">Circular reference to #/components/schemas/google.protobuf.Struct (simplified)</param>
        /// <param name="listValue">listValue</param>
        public Value1(ListValue listValue1, Option<NullValueEnum?> nullValue = default, Option<decimal?> numberValue = default, Option<string?> stringValue = default, Option<bool?> boolValue = default, Option<Object?> structValue = default, Option<ListValue?> listValue = default)
        {
            ListValue1 = listValue1;
            NullValueOption = nullValue;
            NumberValueOption = numberValue;
            StringValueOption = stringValue;
            BoolValueOption = boolValue;
            StructValueOption = structValue;
            ListValueOption = listValue;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines NullValue
        /// </summary>
        public enum NullValueEnum
        {
            /// <summary>
            /// Enum Order0valueNULLVALUEdescriptionmaturityGAexposurePUBLIC for value: {\&quot;order\&quot;:0,\&quot;value\&quot;:\&quot;NULL_VALUE\&quot;,\&quot;description\&quot;:\&quot;\&quot;,\&quot;maturity\&quot;:\&quot;GA\&quot;,\&quot;exposure\&quot;:\&quot;PUBLIC\&quot;}
            /// </summary>
            Order0valueNULLVALUEdescriptionmaturityGAexposurePUBLIC = 1
        }

        /// <summary>
        /// Returns a <see cref="NullValueEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static NullValueEnum NullValueEnumFromString(string value)
        {
            if (value.Equals("{\"order\":0,\"value\":\"NULL_VALUE\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return NullValueEnum.Order0valueNULLVALUEdescriptionmaturityGAexposurePUBLIC;

            throw new NotImplementedException($"Could not convert value to type NullValueEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="NullValueEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NullValueEnum? NullValueEnumFromStringOrDefault(string value)
        {
            if (value.Equals("{\"order\":0,\"value\":\"NULL_VALUE\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}"))
                return NullValueEnum.Order0valueNULLVALUEdescriptionmaturityGAexposurePUBLIC;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="NullValueEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string NullValueEnumToJsonValue(NullValueEnum? value)
        {
            if (value == NullValueEnum.Order0valueNULLVALUEdescriptionmaturityGAexposurePUBLIC)
                return "{\"order\":0,\"value\":\"NULL_VALUE\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of NullValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NullValueEnum?> NullValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets NullValue
        /// </summary>
        [JsonPropertyName("nullValue")]
        public NullValueEnum? NullValue { get { return this.NullValueOption; } set { this.NullValueOption = new(value); } }

        /// <summary>
        /// Gets or Sets NullValue1
        /// </summary>
        public NullValue? NullValue1 { get; set; }

        /// <summary>
        /// Gets or Sets NumberValue1
        /// </summary>
        public NumberValue? NumberValue1 { get; set; }

        /// <summary>
        /// Gets or Sets StringValue1
        /// </summary>
        public StringValue? StringValue1 { get; set; }

        /// <summary>
        /// Gets or Sets BoolValue1
        /// </summary>
        public BoolValue? BoolValue1 { get; set; }

        /// <summary>
        /// Gets or Sets StructValue1
        /// </summary>
        public StructValue? StructValue1 { get; set; }

        /// <summary>
        /// Gets or Sets ListValue1
        /// </summary>
        public ListValue? ListValue1 { get; set; }

        /// <summary>
        /// Used to track the state of NumberValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> NumberValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets NumberValue
        /// </summary>
        [JsonPropertyName("numberValue")]
        public decimal? NumberValue { get { return this.NumberValueOption; } set { this.NumberValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of StringValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StringValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets StringValue
        /// </summary>
        [JsonPropertyName("stringValue")]
        public string? StringValue { get { return this.StringValueOption; } set { this.StringValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of BoolValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> BoolValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets BoolValue
        /// </summary>
        [JsonPropertyName("boolValue")]
        public bool? BoolValue { get { return this.BoolValueOption; } set { this.BoolValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of StructValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> StructValueOption { get; private set; }

        /// <summary>
        /// Circular reference to #/components/schemas/google.protobuf.Struct (simplified)
        /// </summary>
        /// <value>Circular reference to #/components/schemas/google.protobuf.Struct (simplified)</value>
        [JsonPropertyName("structValue")]
        public Object? StructValue { get { return this.StructValueOption; } set { this.StructValueOption = new(value); } }

        /// <summary>
        /// Used to track the state of ListValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ListValue?> ListValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets ListValue
        /// </summary>
        [JsonPropertyName("listValue")]
        public ListValue? ListValue { get { return this.ListValueOption; } set { this.ListValueOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Value1 {\n");
            sb.Append("  NullValue: ").Append(NullValue).Append("\n");
            sb.Append("  NumberValue: ").Append(NumberValue).Append("\n");
            sb.Append("  StringValue: ").Append(StringValue).Append("\n");
            sb.Append("  BoolValue: ").Append(BoolValue).Append("\n");
            sb.Append("  StructValue: ").Append(StructValue).Append("\n");
            sb.Append("  ListValue: ").Append(ListValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Value1" />
    /// </summary>
    public class Value1JsonConverter : JsonConverter<Value1>
    {
        /// <summary>
        /// Deserializes json to <see cref="Value1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Value1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Value1.NullValueEnum?> nullValue = default;
            Option<decimal?> numberValue = default;
            Option<string?> stringValue = default;
            Option<bool?> boolValue = default;
            Option<Object?> structValue = default;
            Option<ListValue?> listValue = default;

            NullValue? nullValue1 = default;
            NumberValue? numberValue1 = default;
            StringValue? stringValue1 = default;
            BoolValue? boolValue1 = default;
            StructValue? structValue1 = default;
            ListValue? listValue1 = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderNullValue1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<NullValue?>(ref utf8JsonReaderNullValue1, jsonSerializerOptions, out nullValue1);

                    Utf8JsonReader utf8JsonReaderNumberValue1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<NumberValue?>(ref utf8JsonReaderNumberValue1, jsonSerializerOptions, out numberValue1);

                    Utf8JsonReader utf8JsonReaderStringValue1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<StringValue?>(ref utf8JsonReaderStringValue1, jsonSerializerOptions, out stringValue1);

                    Utf8JsonReader utf8JsonReaderBoolValue1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<BoolValue?>(ref utf8JsonReaderBoolValue1, jsonSerializerOptions, out boolValue1);

                    Utf8JsonReader utf8JsonReaderStructValue1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<StructValue?>(ref utf8JsonReaderStructValue1, jsonSerializerOptions, out structValue1);

                    Utf8JsonReader utf8JsonReaderListValue1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<ListValue?>(ref utf8JsonReaderListValue1, jsonSerializerOptions, out listValue1);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "nullValue":
                            string? nullValueRawValue = utf8JsonReader.GetString();
                            if (nullValueRawValue != null)
                                nullValue = new Option<Value1.NullValueEnum?>(Value1.NullValueEnumFromStringOrDefault(nullValueRawValue));
                            break;
                        case "numberValue":
                            numberValue = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "stringValue":
                            stringValue = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "boolValue":
                            boolValue = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "structValue":
                            structValue = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "listValue":
                            listValue = new Option<ListValue?>(JsonSerializer.Deserialize<ListValue>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (nullValue.IsSet && nullValue.Value == null)
                throw new ArgumentNullException(nameof(nullValue), "Property is not nullable for class Value1.");

            if (numberValue.IsSet && numberValue.Value == null)
                throw new ArgumentNullException(nameof(numberValue), "Property is not nullable for class Value1.");

            if (stringValue.IsSet && stringValue.Value == null)
                throw new ArgumentNullException(nameof(stringValue), "Property is not nullable for class Value1.");

            if (boolValue.IsSet && boolValue.Value == null)
                throw new ArgumentNullException(nameof(boolValue), "Property is not nullable for class Value1.");

            if (structValue.IsSet && structValue.Value == null)
                throw new ArgumentNullException(nameof(structValue), "Property is not nullable for class Value1.");

            if (listValue.IsSet && listValue.Value == null)
                throw new ArgumentNullException(nameof(listValue), "Property is not nullable for class Value1.");

            if (nullValue1 != null)
                return new Value1(nullValue1, nullValue, numberValue, stringValue, boolValue, structValue, listValue);

            if (numberValue1 != null)
                return new Value1(numberValue1, nullValue, numberValue, stringValue, boolValue, structValue, listValue);

            if (stringValue1 != null)
                return new Value1(stringValue1, nullValue, numberValue, stringValue, boolValue, structValue, listValue);

            if (boolValue1 != null)
                return new Value1(boolValue1, nullValue, numberValue, stringValue, boolValue, structValue, listValue);

            if (structValue1 != null)
                return new Value1(structValue1, nullValue, numberValue, stringValue, boolValue, structValue, listValue);

            if (listValue1 != null)
                return new Value1(listValue1, nullValue, numberValue, stringValue, boolValue, structValue, listValue);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="Value1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="value1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Value1 value1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, value1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Value1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="value1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Value1 value1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (value1.StringValueOption.IsSet && value1.StringValue == null)
                throw new ArgumentNullException(nameof(value1.StringValue), "Property is required for class Value1.");

            if (value1.StructValueOption.IsSet && value1.StructValue == null)
                throw new ArgumentNullException(nameof(value1.StructValue), "Property is required for class Value1.");

            if (value1.ListValueOption.IsSet && value1.ListValue == null)
                throw new ArgumentNullException(nameof(value1.ListValue), "Property is required for class Value1.");

            var nullValueRawValue = Value1.NullValueEnumToJsonValue(value1.NullValueOption.Value!.Value);
            writer.WriteString("nullValue", nullValueRawValue);
            if (value1.NumberValueOption.IsSet)
                writer.WriteNumber("numberValue", value1.NumberValueOption.Value!.Value);

            if (value1.StringValueOption.IsSet)
                writer.WriteString("stringValue", value1.StringValue);

            if (value1.BoolValueOption.IsSet)
                writer.WriteBoolean("boolValue", value1.BoolValueOption.Value!.Value);

            if (value1.StructValueOption.IsSet)
            {
                writer.WritePropertyName("structValue");
                JsonSerializer.Serialize(writer, value1.StructValue, jsonSerializerOptions);
            }
            if (value1.ListValueOption.IsSet)
            {
                writer.WritePropertyName("listValue");
                JsonSerializer.Serialize(writer, value1.ListValue, jsonSerializerOptions);
            }
        }
    }
}
