// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Information about a transaction whose source is a wallet action (store credit) to a customer.
    /// </summary>
    public partial class WalletActionStartOptions1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WalletActionStartOptions1" /> class.
        /// </summary>
        /// <param name="walletActionStartOptions">walletActionStartOptions</param>
        [JsonConstructor]
        public WalletActionStartOptions1(Option<WalletActionStartOptions1?> walletActionStartOptions = default)
        {
            WalletActionStartOptionsOption = walletActionStartOptions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of WalletActionStartOptions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<WalletActionStartOptions1?> WalletActionStartOptionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets WalletActionStartOptions
        /// </summary>
        [JsonPropertyName("walletActionStartOptions")]
        public WalletActionStartOptions1? WalletActionStartOptions { get { return this.WalletActionStartOptionsOption; } set { this.WalletActionStartOptionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WalletActionStartOptions1 {\n");
            sb.Append("  WalletActionStartOptions: ").Append(WalletActionStartOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WalletActionStartOptions1" />
    /// </summary>
    public class WalletActionStartOptions1JsonConverter : JsonConverter<WalletActionStartOptions1>
    {
        /// <summary>
        /// Deserializes json to <see cref="WalletActionStartOptions1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WalletActionStartOptions1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<WalletActionStartOptions1?> walletActionStartOptions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "walletActionStartOptions":
                            walletActionStartOptions = new Option<WalletActionStartOptions1?>(JsonSerializer.Deserialize<WalletActionStartOptions1>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (walletActionStartOptions.IsSet && walletActionStartOptions.Value == null)
                throw new ArgumentNullException(nameof(walletActionStartOptions), "Property is not nullable for class WalletActionStartOptions1.");

            return new WalletActionStartOptions1(walletActionStartOptions);
        }

        /// <summary>
        /// Serializes a <see cref="WalletActionStartOptions1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletActionStartOptions1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WalletActionStartOptions1 walletActionStartOptions1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, walletActionStartOptions1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WalletActionStartOptions1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletActionStartOptions1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WalletActionStartOptions1 walletActionStartOptions1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (walletActionStartOptions1.WalletActionStartOptionsOption.IsSet && walletActionStartOptions1.WalletActionStartOptions == null)
                throw new ArgumentNullException(nameof(walletActionStartOptions1.WalletActionStartOptions), "Property is required for class WalletActionStartOptions1.");

            if (walletActionStartOptions1.WalletActionStartOptionsOption.IsSet)
            {
                writer.WritePropertyName("walletActionStartOptions");
                JsonSerializer.Serialize(writer, walletActionStartOptions1.WalletActionStartOptions, jsonSerializerOptions);
            }
        }
    }
}
