// <auto-generated>
/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WalletActionWithBalance an entity of WalletActionService that align a balance with WalletAction.
    /// </summary>
    public partial class WalletActionWithBalance1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WalletActionWithBalance1" /> class.
        /// </summary>
        /// <param name="walletAction">walletAction</param>
        /// <param name="balance">Remaining balance of the WalletAction.</param>
        [JsonConstructor]
        public WalletActionWithBalance1(Option<WalletAction5?> walletAction = default, Option<string?> balance = default)
        {
            WalletActionOption = walletAction;
            BalanceOption = balance;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of WalletAction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<WalletAction5?> WalletActionOption { get; private set; }

        /// <summary>
        /// Gets or Sets WalletAction
        /// </summary>
        [JsonPropertyName("walletAction")]
        public WalletAction5? WalletAction { get { return this.WalletActionOption; } set { this.WalletActionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Balance
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BalanceOption { get; private set; }

        /// <summary>
        /// Remaining balance of the WalletAction.
        /// </summary>
        /// <value>Remaining balance of the WalletAction.</value>
        [JsonPropertyName("balance")]
        public string? Balance { get { return this.BalanceOption; } set { this.BalanceOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WalletActionWithBalance1 {\n");
            sb.Append("  WalletAction: ").Append(WalletAction).Append("\n");
            sb.Append("  Balance: ").Append(Balance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WalletActionWithBalance1" />
    /// </summary>
    public class WalletActionWithBalance1JsonConverter : JsonConverter<WalletActionWithBalance1>
    {
        /// <summary>
        /// Deserializes json to <see cref="WalletActionWithBalance1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WalletActionWithBalance1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<WalletAction5?> walletAction = default;
            Option<string?> balance = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "walletAction":
                            walletAction = new Option<WalletAction5?>(JsonSerializer.Deserialize<WalletAction5>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "balance":
                            balance = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (walletAction.IsSet && walletAction.Value == null)
                throw new ArgumentNullException(nameof(walletAction), "Property is not nullable for class WalletActionWithBalance1.");

            if (balance.IsSet && balance.Value == null)
                throw new ArgumentNullException(nameof(balance), "Property is not nullable for class WalletActionWithBalance1.");

            return new WalletActionWithBalance1(walletAction, balance);
        }

        /// <summary>
        /// Serializes a <see cref="WalletActionWithBalance1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletActionWithBalance1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WalletActionWithBalance1 walletActionWithBalance1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, walletActionWithBalance1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WalletActionWithBalance1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletActionWithBalance1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WalletActionWithBalance1 walletActionWithBalance1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (walletActionWithBalance1.WalletActionOption.IsSet && walletActionWithBalance1.WalletAction == null)
                throw new ArgumentNullException(nameof(walletActionWithBalance1.WalletAction), "Property is required for class WalletActionWithBalance1.");

            if (walletActionWithBalance1.BalanceOption.IsSet && walletActionWithBalance1.Balance == null)
                throw new ArgumentNullException(nameof(walletActionWithBalance1.Balance), "Property is required for class WalletActionWithBalance1.");

            if (walletActionWithBalance1.WalletActionOption.IsSet)
            {
                writer.WritePropertyName("walletAction");
                JsonSerializer.Serialize(writer, walletActionWithBalance1.WalletAction, jsonSerializerOptions);
            }
            if (walletActionWithBalance1.BalanceOption.IsSet)
                writer.WriteString("balance", walletActionWithBalance1.Balance);
        }
    }
}
