/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ActionSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActionSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActionSettings
        //private ActionSettings instance;

        public ActionSettingsTests()
        {
            // TODO uncomment below to create an instance of ActionSettings
            //instance = new ActionSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActionSettings
        /// </summary>
        [Fact]
        public void ActionSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActionSettings
            //Assert.IsType<ActionSettings>(instance);
        }

        /// <summary>
        /// Test the property 'PermanentActionIds'
        /// </summary>
        [Fact]
        public void PermanentActionIdsTest()
        {
            // TODO unit test for the property 'PermanentActionIds'
        }

        /// <summary>
        /// Test the property 'ReadonlyActionIds'
        /// </summary>
        [Fact]
        public void ReadonlyActionIdsTest()
        {
            // TODO unit test for the property 'ReadonlyActionIds'
        }

        /// <summary>
        /// Test the property 'DisableDelayAddition'
        /// </summary>
        [Fact]
        public void DisableDelayAdditionTest()
        {
            // TODO unit test for the property 'DisableDelayAddition'
        }

        /// <summary>
        /// Test the property 'DisableConditionAddition'
        /// </summary>
        [Fact]
        public void DisableConditionAdditionTest()
        {
            // TODO unit test for the property 'DisableConditionAddition'
        }
    }
}
