/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AggregationType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AggregationTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AggregationType
        //private AggregationType instance;

        public AggregationTypeTests()
        {
            // TODO uncomment below to create an instance of AggregationType
            //instance = new AggregationType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AggregationType
        /// </summary>
        [Fact]
        public void AggregationTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AggregationType
            //Assert.IsType<AggregationType>(instance);
        }
    }
}
