/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationOrigin
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationOriginTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationOrigin
        //private ApplicationOrigin instance;

        public ApplicationOriginTests()
        {
            // TODO uncomment below to create an instance of ApplicationOrigin
            //instance = new ApplicationOrigin();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationOrigin
        /// </summary>
        [Fact]
        public void ApplicationOriginInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationOrigin
            //Assert.IsType<ApplicationOrigin>(instance);
        }

        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Fact]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }

        /// <summary>
        /// Test the property 'AppDefinedExternalId'
        /// </summary>
        [Fact]
        public void AppDefinedExternalIdTest()
        {
            // TODO unit test for the property 'AppDefinedExternalId'
        }
    }
}
