/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CampaignOptions2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CampaignOptions2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CampaignOptions2
        //private CampaignOptions2 instance;

        public CampaignOptions2Tests()
        {
            // TODO uncomment below to create an instance of CampaignOptions2
            //instance = new CampaignOptions2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CampaignOptions2
        /// </summary>
        [Fact]
        public void CampaignOptions2InstanceTest()
        {
            // TODO uncomment below to test "IsType" CampaignOptions2
            //Assert.IsType<CampaignOptions2>(instance);
        }

        /// <summary>
        /// Test the property 'CampaignOptions'
        /// </summary>
        [Fact]
        public void CampaignOptionsTest()
        {
            // TODO unit test for the property 'CampaignOptions'
        }
    }
}
