/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateWalletV2Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateWalletV2ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateWalletV2Response
        //private CreateWalletV2Response instance;

        public CreateWalletV2ResponseTests()
        {
            // TODO uncomment below to create an instance of CreateWalletV2Response
            //instance = new CreateWalletV2Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateWalletV2Response
        /// </summary>
        [Fact]
        public void CreateWalletV2ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateWalletV2Response
            //Assert.IsType<CreateWalletV2Response>(instance);
        }

        /// <summary>
        /// Test the property 'Wallet'
        /// </summary>
        [Fact]
        public void WalletTest()
        {
            // TODO unit test for the property 'Wallet'
        }
    }
}
