/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateRecipientResponse1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateRecipientResponse1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateRecipientResponse1
        //private CreateRecipientResponse1 instance;

        public CreateRecipientResponse1Tests()
        {
            // TODO uncomment below to create an instance of CreateRecipientResponse1
            //instance = new CreateRecipientResponse1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateRecipientResponse1
        /// </summary>
        [Fact]
        public void CreateRecipientResponse1InstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateRecipientResponse1
            //Assert.IsType<CreateRecipientResponse1>(instance);
        }

        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Fact]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }
    }
}
