/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerReference5
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerReference5Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerReference5
        //private CustomerReference5 instance;

        public CustomerReference5Tests()
        {
            // TODO uncomment below to create an instance of CustomerReference5
            //instance = new CustomerReference5();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerReference5
        /// </summary>
        [Fact]
        public void CustomerReference5InstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerReference5
            //Assert.IsType<CustomerReference5>(instance);
        }

        /// <summary>
        /// Test the property 'SourceChannelId'
        /// </summary>
        [Fact]
        public void SourceChannelIdTest()
        {
            // TODO unit test for the property 'SourceChannelId'
        }

        /// <summary>
        /// Test the property 'SourceTenantId'
        /// </summary>
        [Fact]
        public void SourceTenantIdTest()
        {
            // TODO unit test for the property 'SourceTenantId'
        }

        /// <summary>
        /// Test the property 'SourceCustomerId'
        /// </summary>
        [Fact]
        public void SourceCustomerIdTest()
        {
            // TODO unit test for the property 'SourceCustomerId'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
    }
}
