/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ExecuteFromActionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExecuteFromActionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExecuteFromActionRequest
        //private ExecuteFromActionRequest instance;

        public ExecuteFromActionRequestTests()
        {
            // TODO uncomment below to create an instance of ExecuteFromActionRequest
            //instance = new ExecuteFromActionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExecuteFromActionRequest
        /// </summary>
        [Fact]
        public void ExecuteFromActionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExecuteFromActionRequest
            //Assert.IsType<ExecuteFromActionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ActionId'
        /// </summary>
        [Fact]
        public void ActionIdTest()
        {
            // TODO unit test for the property 'ActionId'
        }

        /// <summary>
        /// Test the property 'ActivationId'
        /// </summary>
        [Fact]
        public void ActivationIdTest()
        {
            // TODO unit test for the property 'ActivationId'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'ConfigurationCorrelationId'
        /// </summary>
        [Fact]
        public void ConfigurationCorrelationIdTest()
        {
            // TODO unit test for the property 'ConfigurationCorrelationId'
        }

        /// <summary>
        /// Test the property 'ScheduleId'
        /// </summary>
        [Fact]
        public void ScheduleIdTest()
        {
            // TODO unit test for the property 'ScheduleId'
        }

        /// <summary>
        /// Test the property 'ExternalEntityId'
        /// </summary>
        [Fact]
        public void ExternalEntityIdTest()
        {
            // TODO unit test for the property 'ExternalEntityId'
        }

        /// <summary>
        /// Test the property 'Automation'
        /// </summary>
        [Fact]
        public void AutomationTest()
        {
            // TODO unit test for the property 'Automation'
        }
    }
}
