/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FutureDateActivationOffset
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FutureDateActivationOffsetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FutureDateActivationOffset
        //private FutureDateActivationOffset instance;

        public FutureDateActivationOffsetTests()
        {
            // TODO uncomment below to create an instance of FutureDateActivationOffset
            //instance = new FutureDateActivationOffset();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FutureDateActivationOffset
        /// </summary>
        [Fact]
        public void FutureDateActivationOffsetInstanceTest()
        {
            // TODO uncomment below to test "IsType" FutureDateActivationOffset
            //Assert.IsType<FutureDateActivationOffset>(instance);
        }

        /// <summary>
        /// Test the property 'PreScheduledEventOffsetExpression'
        /// </summary>
        [Fact]
        public void PreScheduledEventOffsetExpressionTest()
        {
            // TODO unit test for the property 'PreScheduledEventOffsetExpression'
        }

        /// <summary>
        /// Test the property 'ScheduledEventOffsetTimeUnit'
        /// </summary>
        [Fact]
        public void ScheduledEventOffsetTimeUnitTest()
        {
            // TODO unit test for the property 'ScheduledEventOffsetTimeUnit'
        }
    }
}
