/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetWalletRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWalletRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWalletRequest
        //private GetWalletRequest instance;

        public GetWalletRequestTests()
        {
            // TODO uncomment below to create an instance of GetWalletRequest
            //instance = new GetWalletRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWalletRequest
        /// </summary>
        [Fact]
        public void GetWalletRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWalletRequest
            //Assert.IsType<GetWalletRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
    }
}
