/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GiftCardSourceInfo2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GiftCardSourceInfo2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GiftCardSourceInfo2
        //private GiftCardSourceInfo2 instance;

        public GiftCardSourceInfo2Tests()
        {
            // TODO uncomment below to create an instance of GiftCardSourceInfo2
            //instance = new GiftCardSourceInfo2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GiftCardSourceInfo2
        /// </summary>
        [Fact]
        public void GiftCardSourceInfo2InstanceTest()
        {
            // TODO uncomment below to test "IsType" GiftCardSourceInfo2
            //Assert.IsType<GiftCardSourceInfo2>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'SourceTenantId'
        /// </summary>
        [Fact]
        public void SourceTenantIdTest()
        {
            // TODO unit test for the property 'SourceTenantId'
        }

        /// <summary>
        /// Test the property 'SourceChannelId'
        /// </summary>
        [Fact]
        public void SourceChannelIdTest()
        {
            // TODO unit test for the property 'SourceChannelId'
        }

        /// <summary>
        /// Test the property 'SourceLocationId'
        /// </summary>
        [Fact]
        public void SourceLocationIdTest()
        {
            // TODO unit test for the property 'SourceLocationId'
        }

        /// <summary>
        /// Test the property 'Initiator'
        /// </summary>
        [Fact]
        public void InitiatorTest()
        {
            // TODO unit test for the property 'Initiator'
        }
    }
}
