/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Identifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentifierTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Identifier
        //private Identifier instance;

        public IdentifierTests()
        {
            // TODO uncomment below to create an instance of Identifier
            //instance = new Identifier();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Identifier
        /// </summary>
        [Fact]
        public void IdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsType" Identifier
            //Assert.IsType<Identifier>(instance);
        }

        /// <summary>
        /// Test the property 'PreinstalledIdentifier'
        /// </summary>
        [Fact]
        public void PreinstalledIdentifierTest()
        {
            // TODO unit test for the property 'PreinstalledIdentifier'
        }

        /// <summary>
        /// Test the property 'AutomationIdentifier'
        /// </summary>
        [Fact]
        public void AutomationIdentifierTest()
        {
            // TODO unit test for the property 'AutomationIdentifier'
        }
    }
}
