/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing IfFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IfFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IfFilter
        //private IfFilter instance;

        public IfFilterTests()
        {
            // TODO uncomment below to create an instance of IfFilter
            //instance = new IfFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IfFilter
        /// </summary>
        [Fact]
        public void IfFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" IfFilter
            //Assert.IsType<IfFilter>(instance);
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

        /// <summary>
        /// Test the property 'TruePostActions'
        /// </summary>
        [Fact]
        public void TruePostActionsTest()
        {
            // TODO unit test for the property 'TruePostActions'
        }

        /// <summary>
        /// Test the property 'FalsePostActions'
        /// </summary>
        [Fact]
        public void FalsePostActionsTest()
        {
            // TODO unit test for the property 'FalsePostActions'
        }

        /// <summary>
        /// Test the property 'TruePostActionsIds'
        /// </summary>
        [Fact]
        public void TruePostActionsIdsTest()
        {
            // TODO unit test for the property 'TruePostActionsIds'
        }

        /// <summary>
        /// Test the property 'FalsePostActionsIds'
        /// </summary>
        [Fact]
        public void FalsePostActionsIdsTest()
        {
            // TODO unit test for the property 'FalsePostActionsIds'
        }
    }
}
