/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InitialOptionsInitialOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InitialOptionsInitialOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InitialOptionsInitialOptions
        //private InitialOptionsInitialOptions instance;

        public InitialOptionsInitialOptionsTests()
        {
            // TODO uncomment below to create an instance of InitialOptionsInitialOptions
            //instance = new InitialOptionsInitialOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InitialOptionsInitialOptions
        /// </summary>
        [Fact]
        public void InitialOptionsInitialOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" InitialOptionsInitialOptions
            //Assert.IsType<InitialOptionsInitialOptions>(instance);
        }

        /// <summary>
        /// Test the property 'GiftCardType'
        /// </summary>
        [Fact]
        public void GiftCardTypeTest()
        {
            // TODO unit test for the property 'GiftCardType'
        }
    }
}
