/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ManualOptions1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManualOptions1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManualOptions1
        //private ManualOptions1 instance;

        public ManualOptions1Tests()
        {
            // TODO uncomment below to create an instance of ManualOptions1
            //instance = new ManualOptions1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManualOptions1
        /// </summary>
        [Fact]
        public void ManualOptions1InstanceTest()
        {
            // TODO uncomment below to test "IsType" ManualOptions1
            //Assert.IsType<ManualOptions1>(instance);
        }

        /// <summary>
        /// Test the property 'ManualOptions'
        /// </summary>
        [Fact]
        public void ManualOptionsTest()
        {
            // TODO unit test for the property 'ManualOptions'
        }
    }
}
