/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NestedResultValue1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NestedResultValue1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NestedResultValue1
        //private NestedResultValue1 instance;

        public NestedResultValue1Tests()
        {
            // TODO uncomment below to create an instance of NestedResultValue1
            //instance = new NestedResultValue1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NestedResultValue1
        /// </summary>
        [Fact]
        public void NestedResultValue1InstanceTest()
        {
            // TODO uncomment below to test "IsType" NestedResultValue1
            //Assert.IsType<NestedResultValue1>(instance);
        }

        /// <summary>
        /// Test the property 'GroupedByValue'
        /// </summary>
        [Fact]
        public void GroupedByValueTest()
        {
            // TODO unit test for the property 'GroupedByValue'
        }

        /// <summary>
        /// Test the property 'Nested'
        /// </summary>
        [Fact]
        public void NestedTest()
        {
            // TODO unit test for the property 'Nested'
        }
    }
}
