/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NestedAggregationResults1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NestedAggregationResults1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NestedAggregationResults1
        //private NestedAggregationResults1 instance;

        public NestedAggregationResults1Tests()
        {
            // TODO uncomment below to create an instance of NestedAggregationResults1
            //instance = new NestedAggregationResults1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NestedAggregationResults1
        /// </summary>
        [Fact]
        public void NestedAggregationResults1InstanceTest()
        {
            // TODO uncomment below to test "IsType" NestedAggregationResults1
            //Assert.IsType<NestedAggregationResults1>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'FieldPath'
        /// </summary>
        [Fact]
        public void FieldPathTest()
        {
            // TODO unit test for the property 'FieldPath'
        }

        /// <summary>
        /// Test the property 'GroupedByValue'
        /// </summary>
        [Fact]
        public void GroupedByValueTest()
        {
            // TODO unit test for the property 'GroupedByValue'
        }
    }
}
