/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Notifications
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotificationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Notifications
        //private Notifications instance;

        public NotificationsTests()
        {
            // TODO uncomment below to create an instance of Notifications
            //instance = new Notifications();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Notifications
        /// </summary>
        [Fact]
        public void NotificationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Notifications
            //Assert.IsType<Notifications>(instance);
        }

        /// <summary>
        /// Test the property 'EmailParams'
        /// </summary>
        [Fact]
        public void EmailParamsTest()
        {
            // TODO unit test for the property 'EmailParams'
        }
    }
}
