/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentMethodRefundOptionsPaymentMethodRefundOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentMethodRefundOptionsPaymentMethodRefundOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentMethodRefundOptionsPaymentMethodRefundOptions
        //private PaymentMethodRefundOptionsPaymentMethodRefundOptions instance;

        public PaymentMethodRefundOptionsPaymentMethodRefundOptionsTests()
        {
            // TODO uncomment below to create an instance of PaymentMethodRefundOptionsPaymentMethodRefundOptions
            //instance = new PaymentMethodRefundOptionsPaymentMethodRefundOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentMethodRefundOptionsPaymentMethodRefundOptions
        /// </summary>
        [Fact]
        public void PaymentMethodRefundOptionsPaymentMethodRefundOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentMethodRefundOptionsPaymentMethodRefundOptions
            //Assert.IsType<PaymentMethodRefundOptionsPaymentMethodRefundOptions>(instance);
        }

        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }

        /// <summary>
        /// Test the property 'Liability'
        /// </summary>
        [Fact]
        public void LiabilityTest()
        {
            // TODO unit test for the property 'Liability'
        }

        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Fact]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }

        /// <summary>
        /// Test the property 'ActiveFundingTransaction'
        /// </summary>
        [Fact]
        public void ActiveFundingTransactionTest()
        {
            // TODO unit test for the property 'ActiveFundingTransaction'
        }
    }
}
