/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody
        //private RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody instance;

        public RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBodyTests()
        {
            // TODO uncomment below to create an instance of RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody
            //instance = new RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody
        /// </summary>
        [Fact]
        public void RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody
            //Assert.IsType<RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
    }
}
