/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody
        //private RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody instance;

        public RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBodyTests()
        {
            // TODO uncomment below to create an instance of RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody
            //instance = new RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody
        /// </summary>
        [Fact]
        public void RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody
            //Assert.IsType<RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Fact]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }

        /// <summary>
        /// Test the property 'SideEffects'
        /// </summary>
        [Fact]
        public void SideEffectsTest()
        {
            // TODO unit test for the property 'SideEffects'
        }
    }
}
