/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Service
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Service
        //private Service instance;

        public ServiceTests()
        {
            // TODO uncomment below to create an instance of Service
            //instance = new Service();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Service
        /// </summary>
        [Fact]
        public void ServiceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Service
            //Assert.IsType<Service>(instance);
        }

        /// <summary>
        /// Test the property 'ServiceMapping'
        /// </summary>
        [Fact]
        public void ServiceMappingTest()
        {
            // TODO unit test for the property 'ServiceMapping'
        }

        /// <summary>
        /// Test the property 'InputMapping'
        /// </summary>
        [Fact]
        public void InputMappingTest()
        {
            // TODO unit test for the property 'InputMapping'
        }

        /// <summary>
        /// Test the property 'OutputMapping'
        /// </summary>
        [Fact]
        public void OutputMappingTest()
        {
            // TODO unit test for the property 'OutputMapping'
        }

        /// <summary>
        /// Test the property 'PostActions'
        /// </summary>
        [Fact]
        public void PostActionsTest()
        {
            // TODO unit test for the property 'PostActions'
        }

        /// <summary>
        /// Test the property 'PostActionsIds'
        /// </summary>
        [Fact]
        public void PostActionsIdsTest()
        {
            // TODO unit test for the property 'PostActionsIds'
        }

        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
    }
}
