/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SetVariablesAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetVariablesActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetVariablesAction
        //private SetVariablesAction instance;

        public SetVariablesActionTests()
        {
            // TODO uncomment below to create an instance of SetVariablesAction
            //instance = new SetVariablesAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetVariablesAction
        /// </summary>
        [Fact]
        public void SetVariablesActionInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetVariablesAction
            //Assert.IsType<SetVariablesAction>(instance);
        }

        /// <summary>
        /// Test the property 'OutputMapping'
        /// </summary>
        [Fact]
        public void OutputMappingTest()
        {
            // TODO unit test for the property 'OutputMapping'
        }

        /// <summary>
        /// Test the property 'OutputSchema'
        /// </summary>
        [Fact]
        public void OutputSchemaTest()
        {
            // TODO unit test for the property 'OutputSchema'
        }

        /// <summary>
        /// Test the property 'PostActionIds'
        /// </summary>
        [Fact]
        public void PostActionIdsTest()
        {
            // TODO unit test for the property 'PostActionIds'
        }
    }
}
