/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SideEffects
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SideEffectsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SideEffects
        //private SideEffects instance;

        public SideEffectsTests()
        {
            // TODO uncomment below to create an instance of SideEffects
            //instance = new SideEffects();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SideEffects
        /// </summary>
        [Fact]
        public void SideEffectsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SideEffects
            //Assert.IsType<SideEffects>(instance);
        }

        /// <summary>
        /// Test the property 'SkipNotifications'
        /// </summary>
        [Fact]
        public void SkipNotificationsTest()
        {
            // TODO unit test for the property 'SkipNotifications'
        }
    }
}
