/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Sorting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SortingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Sorting
        //private Sorting instance;

        public SortingTests()
        {
            // TODO uncomment below to create an instance of Sorting
            //instance = new Sorting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Sorting
        /// </summary>
        [Fact]
        public void SortingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Sorting
            //Assert.IsType<Sorting>(instance);
        }

        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Fact]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
    }
}
