/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing StoreCreditContext1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StoreCreditContext1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StoreCreditContext1
        //private StoreCreditContext1 instance;

        public StoreCreditContext1Tests()
        {
            // TODO uncomment below to create an instance of StoreCreditContext1
            //instance = new StoreCreditContext1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StoreCreditContext1
        /// </summary>
        [Fact]
        public void StoreCreditContext1InstanceTest()
        {
            // TODO uncomment below to test "IsType" StoreCreditContext1
            //Assert.IsType<StoreCreditContext1>(instance);
        }

        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Fact]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }

        /// <summary>
        /// Test the property 'IssuerId'
        /// </summary>
        [Fact]
        public void IssuerIdTest()
        {
            // TODO unit test for the property 'IssuerId'
        }

        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }

        /// <summary>
        /// Test the property 'SourceChannelId'
        /// </summary>
        [Fact]
        public void SourceChannelIdTest()
        {
            // TODO unit test for the property 'SourceChannelId'
        }

        /// <summary>
        /// Test the property 'SourceTenantId'
        /// </summary>
        [Fact]
        public void SourceTenantIdTest()
        {
            // TODO unit test for the property 'SourceTenantId'
        }
    }
}
