/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Trigger
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TriggerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Trigger
        //private Trigger instance;

        public TriggerTests()
        {
            // TODO uncomment below to create an instance of Trigger
            //instance = new Trigger();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Trigger
        /// </summary>
        [Fact]
        public void TriggerInstanceTest()
        {
            // TODO uncomment below to test "IsType" Trigger
            //Assert.IsType<Trigger>(instance);
        }

        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Fact]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }

        /// <summary>
        /// Test the property 'TriggerKey'
        /// </summary>
        [Fact]
        public void TriggerKeyTest()
        {
            // TODO unit test for the property 'TriggerKey'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'ScheduledEventOffset'
        /// </summary>
        [Fact]
        public void ScheduledEventOffsetTest()
        {
            // TODO unit test for the property 'ScheduledEventOffset'
        }

        /// <summary>
        /// Test the property 'RateLimit'
        /// </summary>
        [Fact]
        public void RateLimitTest()
        {
            // TODO unit test for the property 'RateLimit'
        }

        /// <summary>
        /// Test the property 'AutomationConfigMapping'
        /// </summary>
        [Fact]
        public void AutomationConfigMappingTest()
        {
            // TODO unit test for the property 'AutomationConfigMapping'
        }

        /// <summary>
        /// Test the property 'OverrideSchema'
        /// </summary>
        [Fact]
        public void OverrideSchemaTest()
        {
            // TODO unit test for the property 'OverrideSchema'
        }
    }
}
