/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateWalletActionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateWalletActionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateWalletActionResponse
        //private UpdateWalletActionResponse instance;

        public UpdateWalletActionResponseTests()
        {
            // TODO uncomment below to create an instance of UpdateWalletActionResponse
            //instance = new UpdateWalletActionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateWalletActionResponse
        /// </summary>
        [Fact]
        public void UpdateWalletActionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateWalletActionResponse
            //Assert.IsType<UpdateWalletActionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'WalletAction'
        /// </summary>
        [Fact]
        public void WalletActionTest()
        {
            // TODO unit test for the property 'WalletAction'
        }
    }
}
