/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ValueResults1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValueResults1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValueResults1
        //private ValueResults1 instance;

        public ValueResults1Tests()
        {
            // TODO uncomment below to create an instance of ValueResults1
            //instance = new ValueResults1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValueResults1
        /// </summary>
        [Fact]
        public void ValueResults1InstanceTest()
        {
            // TODO uncomment below to test "IsType" ValueResults1
            //Assert.IsType<ValueResults1>(instance);
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
