/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Wallet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Wallet
        //private Wallet instance;

        public WalletTests()
        {
            // TODO uncomment below to create an instance of Wallet
            //instance = new Wallet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Wallet
        /// </summary>
        [Fact]
        public void WalletInstanceTest()
        {
            // TODO uncomment below to test "IsType" Wallet
            //Assert.IsType<Wallet>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Fact]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }

        /// <summary>
        /// Test the property 'GiftCardId'
        /// </summary>
        [Fact]
        public void GiftCardIdTest()
        {
            // TODO unit test for the property 'GiftCardId'
        }

        /// <summary>
        /// Test the property 'CustomerReferences'
        /// </summary>
        [Fact]
        public void CustomerReferencesTest()
        {
            // TODO unit test for the property 'CustomerReferences'
        }

        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

        /// <summary>
        /// Test the property 'UpdatedDate'
        /// </summary>
        [Fact]
        public void UpdatedDateTest()
        {
            // TODO unit test for the property 'UpdatedDate'
        }

        /// <summary>
        /// Test the property 'GiftCardInfo'
        /// </summary>
        [Fact]
        public void GiftCardInfoTest()
        {
            // TODO unit test for the property 'GiftCardInfo'
        }

        /// <summary>
        /// Test the property 'PrimaryContactDetails'
        /// </summary>
        [Fact]
        public void PrimaryContactDetailsTest()
        {
            // TODO unit test for the property 'PrimaryContactDetails'
        }
    }
}
