/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WalletActionExecutionDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletActionExecutionDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletActionExecutionDetails
        //private WalletActionExecutionDetails instance;

        public WalletActionExecutionDetailsTests()
        {
            // TODO uncomment below to create an instance of WalletActionExecutionDetails
            //instance = new WalletActionExecutionDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletActionExecutionDetails
        /// </summary>
        [Fact]
        public void WalletActionExecutionDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletActionExecutionDetails
            //Assert.IsType<WalletActionExecutionDetails>(instance);
        }

        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }

        /// <summary>
        /// Test the property 'ExecutionDate'
        /// </summary>
        [Fact]
        public void ExecutionDateTest()
        {
            // TODO unit test for the property 'ExecutionDate'
        }
    }
}
