/*
 * Rise.ai API Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody
        //private WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody instance;

        public WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBodyTests()
        {
            // TODO uncomment below to create an instance of WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody
            //instance = new WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody
        /// </summary>
        [Fact]
        public void WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody
            //Assert.IsType<WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
    }
}
